/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.travelmanager.api;

import com.travelmanager.model.CreateDriverRequest;
import com.travelmanager.model.Driver;
import com.travelmanager.model.ErrorResponse;
import org.springframework.lang.Nullable;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-11-29T13:20:06.835648045-03:00[America/Sao_Paulo]", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "Drivers", description = "Manutenção de motoristas")
public interface DriversApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_CREATE_DRIVER = "/drivers";
    /**
     * POST /drivers : Cria um novo motorista no sistema.
     * Registra um novo motorista.
     *
     * @param createDriverRequest Dados do motorista a ser criado. (required)
     * @return Motorista criado com sucesso. (status code 201)
     *         or Requisição inválida. Erro de validação de dados (e.g., campos obrigatórios ausentes). (status code 400)
     *         or Não autorizado. (status code 401)
     *         or Proibido. O usuário não tem permissão para criar motoristas. (status code 403)
     *         or Conflito. (Ex: O número da CNH ou CPF já está registrado). (status code 409)
     *         or Erro interno do servidor. (status code 500)
     *         or Erro inesperado não mapeado. (status code 200)
     */
    @Operation(
        operationId = "createDriver",
        summary = "Cria um novo motorista no sistema.",
        description = "Registra um novo motorista.",
        tags = { "Drivers" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Motorista criado com sucesso.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Driver.class))
            }),
            @ApiResponse(responseCode = "400", description = "Requisição inválida. Erro de validação de dados (e.g., campos obrigatórios ausentes).", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Não autorizado.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "403", description = "Proibido. O usuário não tem permissão para criar motoristas.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflito. (Ex: O número da CNH ou CPF já está registrado).", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Erro interno do servidor.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "default", description = "Erro inesperado não mapeado.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = DriversApi.PATH_CREATE_DRIVER,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Driver> createDriver(
        @Parameter(name = "CreateDriverRequest", description = "Dados do motorista a ser criado.", required = true) @Valid @RequestBody CreateDriverRequest createDriverRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"validityCnh\" : \"2027-10-25\", \"rg\" : \"MG 13569569\", \"name\" : \"Fernando Castro de Abreu\", \"cpf\" : \"06556256359\", \"cnhNumber\" : \"2536565936616546\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"dateBirth\" : \"1985-06-15\", \"validityToxicological\" : \"2024-03-01\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_LIST_DRIVERS = "/drivers";
    /**
     * GET /drivers : Lista todos os motoristas da empresa.
     * Recupera uma lista paginada de todos os motoristas registados na empresa.
     *
     * @param limit Número máximo de itens a retornar por página. (optional, default to 50)
     * @param offset Número de itens a ignorar antes de começar a retornar os resultados (para paginação baseada em offset). Use 0 para a primeira página. (optional, default to 0)
     * @return Uma lista paginada de motoristas. (status code 200)
     *         or Não autorizado. Token de autenticação ausente ou inválido. (status code 401)
     *         or Proibido. O usuário está autenticado, mas não tem permissão para listar motoristas. (status code 403)
     *         or Erro interno do servidor. (status code 500)
     *         or Erro inesperado não mapeado. (status code 200)
     */
    @Operation(
        operationId = "listDrivers",
        summary = "Lista todos os motoristas da empresa.",
        description = "Recupera uma lista paginada de todos os motoristas registados na empresa.",
        tags = { "Drivers" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Uma lista paginada de motoristas.", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Driver.class)))
            }),
            @ApiResponse(responseCode = "401", description = "Não autorizado. Token de autenticação ausente ou inválido.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "403", description = "Proibido. O usuário está autenticado, mas não tem permissão para listar motoristas.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Erro interno do servidor.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "default", description = "Erro inesperado não mapeado.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = DriversApi.PATH_LIST_DRIVERS,
        produces = { "application/json" }
    )
    default ResponseEntity<List<Driver>> listDrivers(
        @Min(value = 1) @Max(value = 100) @Parameter(name = "limit", description = "Número máximo de itens a retornar por página.", in = ParameterIn.QUERY) @Valid @RequestParam(value = "limit", required = false, defaultValue = "50") Integer limit,
        @Min(value = 0) @Parameter(name = "offset", description = "Número de itens a ignorar antes de começar a retornar os resultados (para paginação baseada em offset). Use 0 para a primeira página.", in = ParameterIn.QUERY) @Valid @RequestParam(value = "offset", required = false, defaultValue = "0") Integer offset
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"validityCnh\" : \"2027-10-25\", \"rg\" : \"MG 13569569\", \"name\" : \"Fernando Castro de Abreu\", \"cpf\" : \"06556256359\", \"cnhNumber\" : \"2536565936616546\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"dateBirth\" : \"1985-06-15\", \"validityToxicological\" : \"2024-03-01\" }, { \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"validityCnh\" : \"2027-10-25\", \"rg\" : \"MG 13569569\", \"name\" : \"Fernando Castro de Abreu\", \"cpf\" : \"06556256359\", \"cnhNumber\" : \"2536565936616546\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"dateBirth\" : \"1985-06-15\", \"validityToxicological\" : \"2024-03-01\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
