/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.travelmanager.api;

import com.travelmanager.model.CreateDriverReportRequest;
import com.travelmanager.model.CreatePassengerReportRequest;
import com.travelmanager.model.ErrorResponse;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-11-29T13:20:06.835648045-03:00[America/Sao_Paulo]", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "ReportReason", description = "Manutenção de relatos referente a um veículo")
public interface ReportReasonApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_CREATE_DRIVER_REPORT = "/reportReason/driver";
    /**
     * POST /reportReason/driver : Cria um novo relato detalhado de problema por um motorista.
     * Recebe os dados granulares de um motorista sobre um problema no veículo. O *backend* processará esta informação (triagem) e decidirá se uma Ordem de Serviço será criada com base nos requisitos atendidos. 
     *
     * @param createDriverReportRequest Dados do relatório de problema fornecidos pelo motorista. (required)
     * @return O relato foi recebido e aceito para processamento (triagem). O *backend* iniciará a análise para determinar se uma Ordem de Serviço será gerada.  (status code 202)
     *         or Requisição inválida. Erro de validação de dados (e.g., campo obrigatório ausente). (status code 400)
     *         or Não autorizado. Token de autenticação ausente ou inválido. (status code 401)
     *         or Proibido. O usuário está autenticado, mas não tem permissão para submeter o relatório. (status code 403)
     *         or Recurso não encontrado. (Ex: O vehicleId ou driverId referenciado não existe). (status code 404)
     *         or Erro interno do servidor. (Inclui falhas inesperadas de infraestrutura/DB). (status code 500)
     *         or Erro inesperado não mapeado. (status code 200)
     */
    @Operation(
        operationId = "createDriverReport",
        summary = "Cria um novo relato detalhado de problema por um motorista.",
        description = "Recebe os dados granulares de um motorista sobre um problema no veículo. O *backend* processará esta informação (triagem) e decidirá se uma Ordem de Serviço será criada com base nos requisitos atendidos. ",
        tags = { "ReportReason" },
        responses = {
            @ApiResponse(responseCode = "202", description = "O relato foi recebido e aceito para processamento (triagem). O *backend* iniciará a análise para determinar se uma Ordem de Serviço será gerada. "),
            @ApiResponse(responseCode = "400", description = "Requisição inválida. Erro de validação de dados (e.g., campo obrigatório ausente).", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Não autorizado. Token de autenticação ausente ou inválido.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "403", description = "Proibido. O usuário está autenticado, mas não tem permissão para submeter o relatório.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Recurso não encontrado. (Ex: O vehicleId ou driverId referenciado não existe).", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Erro interno do servidor. (Inclui falhas inesperadas de infraestrutura/DB).", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "default", description = "Erro inesperado não mapeado.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ReportReasonApi.PATH_CREATE_DRIVER_REPORT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> createDriverReport(
        @Parameter(name = "CreateDriverReportRequest", description = "Dados do relatório de problema fornecidos pelo motorista.", required = true) @Valid @RequestBody CreateDriverReportRequest createDriverReportRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_CREATE_PASSENGER_REPORT = "/reportReason/passenger";
    /**
     * POST /reportReason/passenger : Cria um novo relato anónimo de problema por um passageiro.
     * Recebe os dados básicos e anónimos de um passageiro sobre um problema no veículo. O *backend* processará esta informação (triagem) e decidirá se uma Ordem de Serviço será criada com base nos requisitos atendidos. 
     *
     * @param createPassengerReportRequest Dados do relatório de problema fornecidos pelo passageiro. (required)
     * @return O relato foi recebido e aceito para processamento (triagem). O *backend* iniciará a análise para determinar se uma Ordem de Serviço será gerada.  (status code 202)
     *         or Requisição inválida. Erro de validação de dados (e.g., campo obrigatório ausente). (status code 400)
     *         or Recurso não encontrado. (Ex: O vehicleId referenciado no relatório não existe). (status code 404)
     *         or Erro interno do servidor. (Inclui falhas inesperadas de infraestrutura/DB). (status code 500)
     *         or Erro inesperado não mapeado. (status code 200)
     */
    @Operation(
        operationId = "createPassengerReport",
        summary = "Cria um novo relato anónimo de problema por um passageiro.",
        description = "Recebe os dados básicos e anónimos de um passageiro sobre um problema no veículo. O *backend* processará esta informação (triagem) e decidirá se uma Ordem de Serviço será criada com base nos requisitos atendidos. ",
        tags = { "PassengerReports" },
        responses = {
            @ApiResponse(responseCode = "202", description = "O relato foi recebido e aceito para processamento (triagem). O *backend* iniciará a análise para determinar se uma Ordem de Serviço será gerada. "),
            @ApiResponse(responseCode = "400", description = "Requisição inválida. Erro de validação de dados (e.g., campo obrigatório ausente).", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Recurso não encontrado. (Ex: O vehicleId referenciado no relatório não existe).", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Erro interno do servidor. (Inclui falhas inesperadas de infraestrutura/DB).", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "default", description = "Erro inesperado não mapeado.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ReportReasonApi.PATH_CREATE_PASSENGER_REPORT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> createPassengerReport(
        @Parameter(name = "CreatePassengerReportRequest", description = "Dados do relatório de problema fornecidos pelo passageiro.", required = true) @Valid @RequestBody CreatePassengerReportRequest createPassengerReportRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
