/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.travelmanager.api;

import com.travelmanager.model.CreateServiceOrdersRequest;
import com.travelmanager.model.ErrorResponse;
import com.travelmanager.model.ServiceOrders;
import java.util.UUID;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-11-29T13:20:06.835648045-03:00[America/Sao_Paulo]", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "ServiceOrders", description = "Manutenção de ordens de serviços para veículos")
public interface ServiceOrdersApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_DELETE_SERVICE_ORDER = "/serviceOrders/{id}";
    /**
     * DELETE /serviceOrders/{id} : Remove uma Ordem de Serviço.
     * Remove permanentemente uma Ordem de Serviço pelo seu ID.
     *
     * @param id Identificador único do recurso a ser operado (e.g., /recursos/{id}). (required)
     * @return Ordem de Serviço removida com sucesso (Sem conteúdo). (status code 204)
     *         or Não autorizado. (status code 401)
     *         or Ordem de Serviço não encontrada. (status code 404)
     *         or Erro interno do servidor. (status code 500)
     */
    @Operation(
        operationId = "deleteServiceOrder",
        summary = "Remove uma Ordem de Serviço.",
        description = "Remove permanentemente uma Ordem de Serviço pelo seu ID.",
        tags = { "ServiceOrders" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Ordem de Serviço removida com sucesso (Sem conteúdo)."),
            @ApiResponse(responseCode = "401", description = "Não autorizado.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Ordem de Serviço não encontrada.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Erro interno do servidor.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = ServiceOrdersApi.PATH_DELETE_SERVICE_ORDER,
        produces = { "application/json" }
    )
    default ResponseEntity<Void> deleteServiceOrder(
        @NotNull @Parameter(name = "id", description = "Identificador único do recurso a ser operado (e.g., /recursos/{id}).", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GET_SERVICE_ORDER_BY_ID = "/serviceOrders/{id}";
    /**
     * GET /serviceOrders/{id} : Recupera os detalhes de uma Ordem de Serviço específica.
     * Retorna a representação completa de uma Ordem de Serviço pelo seu ID único.
     *
     * @param id Identificador único do recurso a ser operado (e.g., /recursos/{id}). (required)
     * @return Detalhes da Ordem de Serviço recuperada. (status code 200)
     *         or Não autorizado. (status code 401)
     *         or Ordem de Serviço não encontrada pelo ID fornecido. (status code 404)
     *         or Erro interno do servidor. (status code 500)
     */
    @Operation(
        operationId = "getServiceOrderById",
        summary = "Recupera os detalhes de uma Ordem de Serviço específica.",
        description = "Retorna a representação completa de uma Ordem de Serviço pelo seu ID único.",
        tags = { "ServiceOrders" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Detalhes da Ordem de Serviço recuperada.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ServiceOrders.class))
            }),
            @ApiResponse(responseCode = "401", description = "Não autorizado.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Ordem de Serviço não encontrada pelo ID fornecido.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Erro interno do servidor.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ServiceOrdersApi.PATH_GET_SERVICE_ORDER_BY_ID,
        produces = { "application/json" }
    )
    default ResponseEntity<ServiceOrders> getServiceOrderById(
        @NotNull @Parameter(name = "id", description = "Identificador único do recurso a ser operado (e.g., /recursos/{id}).", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"cost\" : 450.75, \"serviceDate\" : \"2025-11-24\", \"impact\" : \"blocking\", \"description\" : \"description\", \"type\" : \"internal\", \"priority\" : \"medium\", \"userId\" : \"f0e9d8c7-b6a5-4321-fedc-ba9876543210\", \"maintenanceNature\" : \"corrective\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"vehicleId\" : \"a1b2c3d4-e5f6-7890-1234-567890abcdef\", \"category\" : \"chassis_and_suspension\", \"status\" : \"open\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_REPLACE_SERVICE_ORDER = "/serviceOrders/{id}";
    /**
     * PUT /serviceOrders/{id} : Substitui completamente um registo de Ordem de Serviço.
     * Substitui o registo completo. Requer todos os campos obrigatórios.
     *
     * @param id Identificador único do recurso a ser operado (e.g., /recursos/{id}). (required)
     * @param createServiceOrdersRequest O objeto CreateServiceOrdersRequest completo para substituir o recurso. (required)
     * @return Ordem de Serviço substituída com sucesso. (status code 200)
     *         or Requisição inválida. Erro de validação de dados. (status code 400)
     *         or Ordem de Serviço não encontrada. (status code 404)
     *         or Erro interno do servidor. (status code 500)
     */
    @Operation(
        operationId = "replaceServiceOrder",
        summary = "Substitui completamente um registo de Ordem de Serviço.",
        description = "Substitui o registo completo. Requer todos os campos obrigatórios.",
        tags = { "ServiceOrders" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Ordem de Serviço substituída com sucesso.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ServiceOrders.class))
            }),
            @ApiResponse(responseCode = "400", description = "Requisição inválida. Erro de validação de dados.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Ordem de Serviço não encontrada.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Erro interno do servidor.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = ServiceOrdersApi.PATH_REPLACE_SERVICE_ORDER,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<ServiceOrders> replaceServiceOrder(
        @NotNull @Parameter(name = "id", description = "Identificador único do recurso a ser operado (e.g., /recursos/{id}).", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID id,
        @Parameter(name = "CreateServiceOrdersRequest", description = "O objeto CreateServiceOrdersRequest completo para substituir o recurso.", required = true) @Valid @RequestBody CreateServiceOrdersRequest createServiceOrdersRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"cost\" : 450.75, \"serviceDate\" : \"2025-11-24\", \"impact\" : \"blocking\", \"description\" : \"description\", \"type\" : \"internal\", \"priority\" : \"medium\", \"userId\" : \"f0e9d8c7-b6a5-4321-fedc-ba9876543210\", \"maintenanceNature\" : \"corrective\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"vehicleId\" : \"a1b2c3d4-e5f6-7890-1234-567890abcdef\", \"category\" : \"chassis_and_suspension\", \"status\" : \"open\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_UPDATE_SERVICE_ORDER = "/serviceOrders/{id}";
    /**
     * PATCH /serviceOrders/{id} : Atualiza parcialmente os detalhes de uma Ordem de Serviço.
     * Permite atualizar um ou mais campos (Partial Update).
     *
     * @param id Identificador único do recurso a ser operado (e.g., /recursos/{id}). (required)
     * @param createServiceOrdersRequest O objeto ServiceOrdersRequest com os campos a serem modificados. (required)
     * @return Ordem de Serviço atualizada com sucesso. Retorna o objeto atualizado. (status code 200)
     *         or Requisição inválida. Erro de validação de dados. (status code 400)
     *         or Ordem de Serviço não encontrada. (status code 404)
     *         or Erro interno do servidor. (status code 500)
     */
    @Operation(
        operationId = "updateServiceOrder",
        summary = "Atualiza parcialmente os detalhes de uma Ordem de Serviço.",
        description = "Permite atualizar um ou mais campos (Partial Update).",
        tags = { "ServiceOrders" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Ordem de Serviço atualizada com sucesso. Retorna o objeto atualizado.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ServiceOrders.class))
            }),
            @ApiResponse(responseCode = "400", description = "Requisição inválida. Erro de validação de dados.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Ordem de Serviço não encontrada.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Erro interno do servidor.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = ServiceOrdersApi.PATH_UPDATE_SERVICE_ORDER,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<ServiceOrders> updateServiceOrder(
        @NotNull @Parameter(name = "id", description = "Identificador único do recurso a ser operado (e.g., /recursos/{id}).", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID id,
        @Parameter(name = "CreateServiceOrdersRequest", description = "O objeto ServiceOrdersRequest com os campos a serem modificados.", required = true) @Valid @RequestBody CreateServiceOrdersRequest createServiceOrdersRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"cost\" : 450.75, \"serviceDate\" : \"2025-11-24\", \"impact\" : \"blocking\", \"description\" : \"description\", \"type\" : \"internal\", \"priority\" : \"medium\", \"userId\" : \"f0e9d8c7-b6a5-4321-fedc-ba9876543210\", \"maintenanceNature\" : \"corrective\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"vehicleId\" : \"a1b2c3d4-e5f6-7890-1234-567890abcdef\", \"category\" : \"chassis_and_suspension\", \"status\" : \"open\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
