/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.travelmanager.api;

import com.travelmanager.model.CreateVehicleRequest;
import com.travelmanager.model.ErrorResponse;
import org.springframework.lang.Nullable;
import java.util.UUID;
import com.travelmanager.model.UpdateVehicleRequest;
import com.travelmanager.model.Vehicle;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-11-29T13:20:06.835648045-03:00[America/Sao_Paulo]", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "Vehicles", description = "Manutenção de frota de veículos.")
public interface VehiclesApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_CREATE_VEHICLE = "/vehicles";
    /**
     * POST /vehicles : Cria um novo registo de veículo na frota.
     * Adiciona um novo veículo à frota, validando que a placa de matrícula é única.
     *
     * @param createVehicleRequest O objeto CreateVehicleRequest necessário para criar um novo veículo. (required)
     * @return Veículo criado com sucesso. Retorna o objeto Vehicle completo. (status code 201)
     *         or Requisição inválida. Erro de validação de dados (e.g., campo obrigatório ausente, formato inválido). (status code 400)
     *         or Proibido. O usuário está autenticado, mas não tem permissão para criar veículos. (status code 403)
     *         or Recurso não encontrado. Algum recurso referenciado (ex: um ID de modelo) não existe. (status code 404)
     *         or Conflito. A placa de matrícula ou VIN já está registado noutro veículo. (status code 409)
     *         or Não autorizado. Token de autenticação ausente ou inválido. (status code 401)
     *         or Erro interno do servidor. (status code 500)
     *         or Erro inesperado não mapeado. (status code 200)
     */
    @Operation(
        operationId = "createVehicle",
        summary = "Cria um novo registo de veículo na frota.",
        description = "Adiciona um novo veículo à frota, validando que a placa de matrícula é única.",
        tags = { "Vehicles" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Veículo criado com sucesso. Retorna o objeto Vehicle completo.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Vehicle.class))
            }),
            @ApiResponse(responseCode = "400", description = "Requisição inválida. Erro de validação de dados (e.g., campo obrigatório ausente, formato inválido).", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "403", description = "Proibido. O usuário está autenticado, mas não tem permissão para criar veículos.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Recurso não encontrado. Algum recurso referenciado (ex: um ID de modelo) não existe.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflito. A placa de matrícula ou VIN já está registado noutro veículo.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Não autorizado. Token de autenticação ausente ou inválido.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Erro interno do servidor.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "default", description = "Erro inesperado não mapeado.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth", scopes={ "kjshdfahskfhakjsdfhkjasdhfkadsh" })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = VehiclesApi.PATH_CREATE_VEHICLE,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Vehicle> createVehicle(
        @Parameter(name = "CreateVehicleRequest", description = "O objeto CreateVehicleRequest necessário para criar um novo veículo.", required = true) @Valid @RequestBody CreateVehicleRequest createVehicleRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"renavan\" : \"4566546465\", \"axesNumber\" : 3, \"bodyManufacturer\" : \"Marcopolo\", \"bodyModel\" : \"G6 1200\", \"engineDescription\" : \"B10 M Intercooler\", \"modelYear\" : 2024, \"fuelTankCapacity\" : 500.5, \"hasBathroom\" : true, \"vehicleManufacturer\" : \"Scania\", \"entryMileage\" : 3000000, \"chassisNumber\" : \"BDH546SDFG565465SD5656BR\", \"createdAt\" : \"2025-01-25T10:00:00Z\", \"manufacturerYear\" : 2023, \"licensePlate\" : \"ABC1F34\", \"fleetNumber\" : 1803, \"averageConsumption\" : 2.6, \"model\" : \"520 HP\", \"id\" : \"a1b2c3d4-e5f6-7890-1234-567890abcdef\", \"passengerNumber\" : 50, \"motorNumber\" : \"20234565\", \"status\" : \"available\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_DELETE_VEHICLE = "/vehicles/{id}";
    /**
     * DELETE /vehicles/{id} : Remove um veículo da frota.
     * Remove permanentemente (ou logicamente desativa) um veículo pelo seu ID.
     *
     * @param id Identificador único do recurso a ser operado (e.g., /recursos/{id}). (required)
     * @return Veículo removido com sucesso (Sem conteúdo). (status code 204)
     *         or Não autorizado. (status code 401)
     *         or Proibido. O usuário não tem permissão para remover este recurso. (status code 403)
     *         or Veículo não encontrado. (status code 404)
     *         or Erro interno do servidor. (status code 500)
     *         or Erro ao remover o veículo. (status code 200)
     */
    @Operation(
        operationId = "deleteVehicle",
        summary = "Remove um veículo da frota.",
        description = "Remove permanentemente (ou logicamente desativa) um veículo pelo seu ID.",
        tags = { "Vehicles" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Veículo removido com sucesso (Sem conteúdo)."),
            @ApiResponse(responseCode = "401", description = "Não autorizado.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "403", description = "Proibido. O usuário não tem permissão para remover este recurso.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Veículo não encontrado.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Erro interno do servidor.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "default", description = "Erro ao remover o veículo.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = VehiclesApi.PATH_DELETE_VEHICLE,
        produces = { "application/json" }
    )
    default ResponseEntity<Void> deleteVehicle(
        @NotNull @Parameter(name = "id", description = "Identificador único do recurso a ser operado (e.g., /recursos/{id}).", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GET_VEHICLE_BY_ID = "/vehicles/{id}";
    /**
     * GET /vehicles/{id} : Recupera os detalhes de um veículo específico.
     * Retorna a representação completa de um veículo pelo seu ID único.
     *
     * @param id Identificador único do recurso a ser operado (e.g., /recursos/{id}). (required)
     * @return Detalhes do veículo recuperado. (status code 200)
     *         or Não autorizado. Token de autenticação ausente ou inválido. (status code 401)
     *         or Proibido. O usuário está autenticado, mas não tem permissão de leitura para este veículo. (status code 403)
     *         or Veículo não encontrado pelo ID fornecido. (status code 404)
     *         or Erro interno do servidor. (status code 500)
     *         or Erro inesperado não mapeado. (status code 200)
     */
    @Operation(
        operationId = "getVehicleById",
        summary = "Recupera os detalhes de um veículo específico.",
        description = "Retorna a representação completa de um veículo pelo seu ID único.",
        tags = { "Vehicles" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Detalhes do veículo recuperado.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Vehicle.class))
            }),
            @ApiResponse(responseCode = "401", description = "Não autorizado. Token de autenticação ausente ou inválido.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "403", description = "Proibido. O usuário está autenticado, mas não tem permissão de leitura para este veículo.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Veículo não encontrado pelo ID fornecido.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Erro interno do servidor.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "default", description = "Erro inesperado não mapeado.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = VehiclesApi.PATH_GET_VEHICLE_BY_ID,
        produces = { "application/json" }
    )
    default ResponseEntity<Vehicle> getVehicleById(
        @NotNull @Parameter(name = "id", description = "Identificador único do recurso a ser operado (e.g., /recursos/{id}).", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"renavan\" : \"4566546465\", \"axesNumber\" : 3, \"bodyManufacturer\" : \"Marcopolo\", \"bodyModel\" : \"G6 1200\", \"engineDescription\" : \"B10 M Intercooler\", \"modelYear\" : 2024, \"fuelTankCapacity\" : 500.5, \"hasBathroom\" : true, \"vehicleManufacturer\" : \"Scania\", \"entryMileage\" : 3000000, \"chassisNumber\" : \"BDH546SDFG565465SD5656BR\", \"createdAt\" : \"2025-01-25T10:00:00Z\", \"manufacturerYear\" : 2023, \"licensePlate\" : \"ABC1F34\", \"fleetNumber\" : 1803, \"averageConsumption\" : 2.6, \"model\" : \"520 HP\", \"id\" : \"a1b2c3d4-e5f6-7890-1234-567890abcdef\", \"passengerNumber\" : 50, \"motorNumber\" : \"20234565\", \"status\" : \"available\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_LIST_VEHICLES = "/vehicles";
    /**
     * GET /vehicles : Lista todos os veículos disponíveis na frota.
     * Recupera uma lista paginada de todos os veículos registados na frota, com opções de filtragem por status operacional.
     *
     * @param limit Número máximo de itens a retornar por página. (optional, default to 50)
     * @param offset Número de itens a ignorar antes de começar a retornar os resultados (para paginação baseada em offset). Use 0 para a primeira página. (optional, default to 0)
     * @return Uma lista paginada de veículos. (status code 200)
     *         or Não autorizado. Token de autenticação ausente ou inválido. (status code 401)
     *         or Erro interno do servidor. (status code 500)
     *         or Erro inesperado não mapeado. (status code 200)
     */
    @Operation(
        operationId = "listVehicles",
        summary = "Lista todos os veículos disponíveis na frota.",
        description = "Recupera uma lista paginada de todos os veículos registados na frota, com opções de filtragem por status operacional.",
        tags = { "Vehicles" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Uma lista paginada de veículos.", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Vehicle.class)))
            }),
            @ApiResponse(responseCode = "401", description = "Não autorizado. Token de autenticação ausente ou inválido.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Erro interno do servidor.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "default", description = "Erro inesperado não mapeado.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth", scopes={ "kjshdfahskfhakjsdfhkjasdhfkadsh" })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = VehiclesApi.PATH_LIST_VEHICLES,
        produces = { "application/json" }
    )
    default ResponseEntity<List<Vehicle>> listVehicles(
        @Min(value = 1) @Max(value = 100) @Parameter(name = "limit", description = "Número máximo de itens a retornar por página.", in = ParameterIn.QUERY) @Valid @RequestParam(value = "limit", required = false, defaultValue = "50") Integer limit,
        @Min(value = 0) @Parameter(name = "offset", description = "Número de itens a ignorar antes de começar a retornar os resultados (para paginação baseada em offset). Use 0 para a primeira página.", in = ParameterIn.QUERY) @Valid @RequestParam(value = "offset", required = false, defaultValue = "0") Integer offset
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"renavan\" : \"4566546465\", \"axesNumber\" : 3, \"bodyManufacturer\" : \"Marcopolo\", \"bodyModel\" : \"G6 1200\", \"engineDescription\" : \"B10 M Intercooler\", \"modelYear\" : 2024, \"fuelTankCapacity\" : 500.5, \"hasBathroom\" : true, \"vehicleManufacturer\" : \"Scania\", \"entryMileage\" : 3000000, \"chassisNumber\" : \"BDH546SDFG565465SD5656BR\", \"createdAt\" : \"2025-01-25T10:00:00Z\", \"manufacturerYear\" : 2023, \"licensePlate\" : \"ABC1F34\", \"fleetNumber\" : 1803, \"averageConsumption\" : 2.6, \"model\" : \"520 HP\", \"id\" : \"a1b2c3d4-e5f6-7890-1234-567890abcdef\", \"passengerNumber\" : 50, \"motorNumber\" : \"20234565\", \"status\" : \"available\" }, { \"renavan\" : \"4566546465\", \"axesNumber\" : 3, \"bodyManufacturer\" : \"Marcopolo\", \"bodyModel\" : \"G6 1200\", \"engineDescription\" : \"B10 M Intercooler\", \"modelYear\" : 2024, \"fuelTankCapacity\" : 500.5, \"hasBathroom\" : true, \"vehicleManufacturer\" : \"Scania\", \"entryMileage\" : 3000000, \"chassisNumber\" : \"BDH546SDFG565465SD5656BR\", \"createdAt\" : \"2025-01-25T10:00:00Z\", \"manufacturerYear\" : 2023, \"licensePlate\" : \"ABC1F34\", \"fleetNumber\" : 1803, \"averageConsumption\" : 2.6, \"model\" : \"520 HP\", \"id\" : \"a1b2c3d4-e5f6-7890-1234-567890abcdef\", \"passengerNumber\" : 50, \"motorNumber\" : \"20234565\", \"status\" : \"available\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_REPLACE_VEHICLE = "/vehicles/{id}";
    /**
     * PUT /vehicles/{id} : Substitui completamente um registo de veículo.
     * Substitui o registo completo do veículo pelo ID. Requer todos os campos obrigatórios.
     *
     * @param id Identificador único do recurso a ser operado (e.g., /recursos/{id}). (required)
     * @param createVehicleRequest O objeto CreateVehicleRequest completo para substituir o recurso. (required)
     * @return Veículo substituído com sucesso. (status code 200)
     *         or Requisição inválida. Erro de validação de dados. (status code 400)
     *         or Não autorizado. (status code 401)
     *         or Proibido. O usuário não tem permissão para alterar este recurso. (status code 403)
     *         or Veículo não encontrado. (status code 404)
     *         or Conflito. (Ex: A nova placa já está em uso por outro veículo). (status code 409)
     *         or Erro interno do servidor. (status code 500)
     *         or Erro ao substituir o veículo. (status code 200)
     */
    @Operation(
        operationId = "replaceVehicle",
        summary = "Substitui completamente um registo de veículo.",
        description = "Substitui o registo completo do veículo pelo ID. Requer todos os campos obrigatórios.",
        tags = { "Vehicles" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Veículo substituído com sucesso.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Vehicle.class))
            }),
            @ApiResponse(responseCode = "400", description = "Requisição inválida. Erro de validação de dados.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Não autorizado.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "403", description = "Proibido. O usuário não tem permissão para alterar este recurso.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Veículo não encontrado.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflito. (Ex: A nova placa já está em uso por outro veículo).", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Erro interno do servidor.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "default", description = "Erro ao substituir o veículo.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = VehiclesApi.PATH_REPLACE_VEHICLE,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Vehicle> replaceVehicle(
        @NotNull @Parameter(name = "id", description = "Identificador único do recurso a ser operado (e.g., /recursos/{id}).", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID id,
        @Parameter(name = "CreateVehicleRequest", description = "O objeto CreateVehicleRequest completo para substituir o recurso.", required = true) @Valid @RequestBody CreateVehicleRequest createVehicleRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"renavan\" : \"4566546465\", \"axesNumber\" : 3, \"bodyManufacturer\" : \"Marcopolo\", \"bodyModel\" : \"G6 1200\", \"engineDescription\" : \"B10 M Intercooler\", \"modelYear\" : 2024, \"fuelTankCapacity\" : 500.5, \"hasBathroom\" : true, \"vehicleManufacturer\" : \"Scania\", \"entryMileage\" : 3000000, \"chassisNumber\" : \"BDH546SDFG565465SD5656BR\", \"createdAt\" : \"2025-01-25T10:00:00Z\", \"manufacturerYear\" : 2023, \"licensePlate\" : \"ABC1F34\", \"fleetNumber\" : 1803, \"averageConsumption\" : 2.6, \"model\" : \"520 HP\", \"id\" : \"a1b2c3d4-e5f6-7890-1234-567890abcdef\", \"passengerNumber\" : 50, \"motorNumber\" : \"20234565\", \"status\" : \"available\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_UPDATE_VEHICLE = "/vehicles/{id}";
    /**
     * PATCH /vehicles/{id} : Atualiza parcialmente os detalhes de um veículo.
     * Permite atualizar um ou mais campos do veículo sem enviar o objeto completo (Partial Update).
     *
     * @param id Identificador único do recurso a ser operado (e.g., /recursos/{id}). (required)
     * @param updateVehicleRequest O objeto UpdateVehicleRequest com os campos a serem modificados. (required)
     * @return Veículo atualizado com sucesso. Retorna o objeto atualizado. (status code 200)
     *         or Requisição inválida. Erro de validação de dados. (status code 400)
     *         or Não autorizado. (status code 401)
     *         or Proibido. O usuário não tem permissão para modificar este recurso. (status code 403)
     *         or Veículo não encontrado. (status code 404)
     *         or Conflito. (Ex: A nova placa já está em uso por outro veículo). (status code 409)
     *         or Erro interno do servidor. (status code 500)
     *         or Erro ao atualizar o veículo. (status code 200)
     */
    @Operation(
        operationId = "updateVehicle",
        summary = "Atualiza parcialmente os detalhes de um veículo.",
        description = "Permite atualizar um ou mais campos do veículo sem enviar o objeto completo (Partial Update).",
        tags = { "Vehicles" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Veículo atualizado com sucesso. Retorna o objeto atualizado.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Vehicle.class))
            }),
            @ApiResponse(responseCode = "400", description = "Requisição inválida. Erro de validação de dados.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Não autorizado.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "403", description = "Proibido. O usuário não tem permissão para modificar este recurso.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Veículo não encontrado.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflito. (Ex: A nova placa já está em uso por outro veículo).", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Erro interno do servidor.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "default", description = "Erro ao atualizar o veículo.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = VehiclesApi.PATH_UPDATE_VEHICLE,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Vehicle> updateVehicle(
        @NotNull @Parameter(name = "id", description = "Identificador único do recurso a ser operado (e.g., /recursos/{id}).", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID id,
        @Parameter(name = "UpdateVehicleRequest", description = "O objeto UpdateVehicleRequest com os campos a serem modificados.", required = true) @Valid @RequestBody UpdateVehicleRequest updateVehicleRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"renavan\" : \"4566546465\", \"axesNumber\" : 3, \"bodyManufacturer\" : \"Marcopolo\", \"bodyModel\" : \"G6 1200\", \"engineDescription\" : \"B10 M Intercooler\", \"modelYear\" : 2024, \"fuelTankCapacity\" : 500.5, \"hasBathroom\" : true, \"vehicleManufacturer\" : \"Scania\", \"entryMileage\" : 3000000, \"chassisNumber\" : \"BDH546SDFG565465SD5656BR\", \"createdAt\" : \"2025-01-25T10:00:00Z\", \"manufacturerYear\" : 2023, \"licensePlate\" : \"ABC1F34\", \"fleetNumber\" : 1803, \"averageConsumption\" : 2.6, \"model\" : \"520 HP\", \"id\" : \"a1b2c3d4-e5f6-7890-1234-567890abcdef\", \"passengerNumber\" : 50, \"motorNumber\" : \"20234565\", \"status\" : \"available\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"traceId\" : \"traceId\", \"errorCode\" : \"errorCode\", \"details\" : [ { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" }, { \"field\" : \"field\", \"issue\" : \"issue\", \"targetValue\" : \"targetValue\" } ], \"message\" : \"message\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
