/* tslint:disable */
/* eslint-disable */
/**
 * Travel Manager - API de Gestão de recursos de transporte rodoviário
 * Especificação modular da API de back-end. Todos os schemas e paths estão em ficheiros separados (specs/). Use um agregador OpenAPI (como o ReDoc ou Swagger UI) para visualizar a documentação completa.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ferdxavier@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BaseEntityProperties
 */
export interface BaseEntityProperties {
    /**
     * ID único gerado pelo sistema.
     * @type {string}
     * @memberof BaseEntityProperties
     */
    id?: string;
    /**
     * Timestamp de criação do registro.
     * @type {Date}
     * @memberof BaseEntityProperties
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the BaseEntityProperties interface.
 */
export function instanceOfBaseEntityProperties(value: object): value is BaseEntityProperties {
    return true;
}

export function BaseEntityPropertiesFromJSON(json: any): BaseEntityProperties {
    return BaseEntityPropertiesFromJSONTyped(json, false);
}

export function BaseEntityPropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseEntityProperties {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function BaseEntityPropertiesToJSON(json: any): BaseEntityProperties {
    return BaseEntityPropertiesToJSONTyped(json, false);
}

export function BaseEntityPropertiesToJSONTyped(value?: BaseEntityProperties | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    };
}

