/* tslint:disable */
/* eslint-disable */
/**
 * Travel Manager - API de Gestão de recursos de transporte rodoviário
 * Especificação modular da API de back-end. Todos os schemas e paths estão em ficheiros separados (specs/). Use um agregador OpenAPI (como o ReDoc ou Swagger UI) para visualizar a documentação completa.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ferdxavier@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Impact } from './Impact';
import {
    ImpactFromJSON,
    ImpactFromJSONTyped,
    ImpactToJSON,
    ImpactToJSONTyped,
} from './Impact';
import type { Status } from './Status';
import {
    StatusFromJSON,
    StatusFromJSONTyped,
    StatusToJSON,
    StatusToJSONTyped,
} from './Status';
import type { Type } from './Type';
import {
    TypeFromJSON,
    TypeFromJSONTyped,
    TypeToJSON,
    TypeToJSONTyped,
} from './Type';
import type { Category } from './Category';
import {
    CategoryFromJSON,
    CategoryFromJSONTyped,
    CategoryToJSON,
    CategoryToJSONTyped,
} from './Category';
import type { MaintenanceNature } from './MaintenanceNature';
import {
    MaintenanceNatureFromJSON,
    MaintenanceNatureFromJSONTyped,
    MaintenanceNatureToJSON,
    MaintenanceNatureToJSONTyped,
} from './MaintenanceNature';
import type { Priority } from './Priority';
import {
    PriorityFromJSON,
    PriorityFromJSONTyped,
    PriorityToJSON,
    PriorityToJSONTyped,
} from './Priority';

/**
 * Dados necessários para criar uma nova ordem de serviço.
 * @export
 * @interface CreateServiceOrdersRequest
 */
export interface CreateServiceOrdersRequest {
    /**
     * ID do veículo ao qual a ordem de serviço está associada.
     * @type {string}
     * @memberof CreateServiceOrdersRequest
     */
    vehicleId: string;
    /**
     * ID do usuário que inseriu/criou a ordem de serviço.
     * @type {string}
     * @memberof CreateServiceOrdersRequest
     */
    userId: string;
    /**
     * Descrição detalhada do problema ou serviço a ser realizado.
     * @type {string}
     * @memberof CreateServiceOrdersRequest
     */
    description: string;
    /**
     * 
     * @type {Type}
     * @memberof CreateServiceOrdersRequest
     */
    type: Type;
    /**
     * 
     * @type {Category}
     * @memberof CreateServiceOrdersRequest
     */
    category: Category;
    /**
     * 
     * @type {MaintenanceNature}
     * @memberof CreateServiceOrdersRequest
     */
    maintenanceNature: MaintenanceNature;
    /**
     * 
     * @type {Impact}
     * @memberof CreateServiceOrdersRequest
     */
    impact: Impact;
    /**
     * 
     * @type {Priority}
     * @memberof CreateServiceOrdersRequest
     */
    priority: Priority;
    /**
     * Data em que o serviço foi agendado ou concluído.
     * @type {Date}
     * @memberof CreateServiceOrdersRequest
     */
    serviceDate?: Date | null;
    /**
     * 
     * @type {Status}
     * @memberof CreateServiceOrdersRequest
     */
    status?: Status;
}



/**
 * Check if a given object implements the CreateServiceOrdersRequest interface.
 */
export function instanceOfCreateServiceOrdersRequest(value: object): value is CreateServiceOrdersRequest {
    if (!('vehicleId' in value) || value['vehicleId'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('maintenanceNature' in value) || value['maintenanceNature'] === undefined) return false;
    if (!('impact' in value) || value['impact'] === undefined) return false;
    if (!('priority' in value) || value['priority'] === undefined) return false;
    return true;
}

export function CreateServiceOrdersRequestFromJSON(json: any): CreateServiceOrdersRequest {
    return CreateServiceOrdersRequestFromJSONTyped(json, false);
}

export function CreateServiceOrdersRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateServiceOrdersRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'vehicleId': json['vehicleId'],
        'userId': json['userId'],
        'description': json['description'],
        'type': TypeFromJSON(json['type']),
        'category': CategoryFromJSON(json['category']),
        'maintenanceNature': MaintenanceNatureFromJSON(json['maintenanceNature']),
        'impact': ImpactFromJSON(json['impact']),
        'priority': PriorityFromJSON(json['priority']),
        'serviceDate': json['serviceDate'] == null ? undefined : (new Date(json['serviceDate'])),
        'status': json['status'] == null ? undefined : StatusFromJSON(json['status']),
    };
}

export function CreateServiceOrdersRequestToJSON(json: any): CreateServiceOrdersRequest {
    return CreateServiceOrdersRequestToJSONTyped(json, false);
}

export function CreateServiceOrdersRequestToJSONTyped(value?: CreateServiceOrdersRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'vehicleId': value['vehicleId'],
        'userId': value['userId'],
        'description': value['description'],
        'type': TypeToJSON(value['type']),
        'category': CategoryToJSON(value['category']),
        'maintenanceNature': MaintenanceNatureToJSON(value['maintenanceNature']),
        'impact': ImpactToJSON(value['impact']),
        'priority': PriorityToJSON(value['priority']),
        'serviceDate': value['serviceDate'] == null ? value['serviceDate'] : value['serviceDate'].toISOString().substring(0,10),
        'status': StatusToJSON(value['status']),
    };
}

