/* tslint:disable */
/* eslint-disable */
/**
 * Travel Manager - API de Gestão de recursos de transporte rodoviário
 * Especificação modular da API de back-end. Todos os schemas e paths estão em ficheiros separados (specs/). Use um agregador OpenAPI (como o ReDoc ou Swagger UI) para visualizar a documentação completa.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ferdxavier@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Dados necessários para criar um veículo (sem o ID gerado pelo sistema e timestamps).
 * @export
 * @interface CreateVehicleRequest
 */
export interface CreateVehicleRequest {
    /**
     * Placa do veículo. Formato Mercosul (LLLNLNN).
     * @type {string}
     * @memberof CreateVehicleRequest
     */
    licensePlate: string;
    /**
     * Modelo e nome do veículo.
     * @type {string}
     * @memberof CreateVehicleRequest
     */
    model: string;
    /**
     * Fabricante do veículo.
     * @type {string}
     * @memberof CreateVehicleRequest
     */
    vehicleManufacturer: string;
    /**
     * Ano do Modelo do veículo.
     * @type {number}
     * @memberof CreateVehicleRequest
     */
    modelYear: number;
    /**
     * Ano de fabricação do veículo.
     * @type {number}
     * @memberof CreateVehicleRequest
     */
    manufacturerYear: number;
    /**
     * Número do RENAVAN do veículo.
     * @type {string}
     * @memberof CreateVehicleRequest
     */
    renavan?: string;
    /**
     * Em caso de veículo de transporte, o número de passageiros.
     * @type {number}
     * @memberof CreateVehicleRequest
     */
    passengerNumber: number;
    /**
     * Número do motor do veículo.
     * @type {string}
     * @memberof CreateVehicleRequest
     */
    motorNumber?: string;
    /**
     * Número do chassis do veículo.
     * @type {string}
     * @memberof CreateVehicleRequest
     */
    chassisNumber: string;
    /**
     * Número interno que corresponte ao id do veículo da frota da empresa.
     * @type {number}
     * @memberof CreateVehicleRequest
     */
    fleetNumber?: number;
    /**
     * Capacidade do tanque de combustivel do veículo.
     * @type {number}
     * @memberof CreateVehicleRequest
     */
    fuelTankCapacity?: number;
    /**
     * Quilometragem do veículo na entrada da empresa (no cadastro).
     * @type {number}
     * @memberof CreateVehicleRequest
     */
    entryMileage?: number;
    /**
     * Média de Quilômetros por litro de conbustivel.
     * @type {number}
     * @memberof CreateVehicleRequest
     */
    averageConsumption?: number;
    /**
     * Fabricante da carroceria.
     * @type {string}
     * @memberof CreateVehicleRequest
     */
    bodyManufacturer?: string;
    /**
     * Nome do modelo da carroceria.
     * @type {string}
     * @memberof CreateVehicleRequest
     */
    bodyModel?: string;
    /**
     * Número de eixos que o veículo possui.
     * @type {number}
     * @memberof CreateVehicleRequest
     */
    axesNumber?: number;
    /**
     * Descrição do motor.
     * @type {string}
     * @memberof CreateVehicleRequest
     */
    engineDescription?: string;
    /**
     * Se o veículo possui banheiro
     * @type {boolean}
     * @memberof CreateVehicleRequest
     */
    hasBathroom: boolean;
    /**
     * Status operacional atual/desejado do veículo.
     * @type {string}
     * @memberof CreateVehicleRequest
     */
    status: CreateVehicleRequestStatusEnum;
}


/**
 * @export
 */
export const CreateVehicleRequestStatusEnum = {
    Available: 'available',
    Maintenance: 'maintenance',
    Retired: 'retired'
} as const;
export type CreateVehicleRequestStatusEnum = typeof CreateVehicleRequestStatusEnum[keyof typeof CreateVehicleRequestStatusEnum];


/**
 * Check if a given object implements the CreateVehicleRequest interface.
 */
export function instanceOfCreateVehicleRequest(value: object): value is CreateVehicleRequest {
    if (!('licensePlate' in value) || value['licensePlate'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('vehicleManufacturer' in value) || value['vehicleManufacturer'] === undefined) return false;
    if (!('modelYear' in value) || value['modelYear'] === undefined) return false;
    if (!('manufacturerYear' in value) || value['manufacturerYear'] === undefined) return false;
    if (!('passengerNumber' in value) || value['passengerNumber'] === undefined) return false;
    if (!('chassisNumber' in value) || value['chassisNumber'] === undefined) return false;
    if (!('hasBathroom' in value) || value['hasBathroom'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function CreateVehicleRequestFromJSON(json: any): CreateVehicleRequest {
    return CreateVehicleRequestFromJSONTyped(json, false);
}

export function CreateVehicleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateVehicleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'licensePlate': json['licensePlate'],
        'model': json['model'],
        'vehicleManufacturer': json['vehicleManufacturer'],
        'modelYear': json['modelYear'],
        'manufacturerYear': json['manufacturerYear'],
        'renavan': json['renavan'] == null ? undefined : json['renavan'],
        'passengerNumber': json['passengerNumber'],
        'motorNumber': json['motorNumber'] == null ? undefined : json['motorNumber'],
        'chassisNumber': json['chassisNumber'],
        'fleetNumber': json['fleetNumber'] == null ? undefined : json['fleetNumber'],
        'fuelTankCapacity': json['fuelTankCapacity'] == null ? undefined : json['fuelTankCapacity'],
        'entryMileage': json['entryMileage'] == null ? undefined : json['entryMileage'],
        'averageConsumption': json['averageConsumption'] == null ? undefined : json['averageConsumption'],
        'bodyManufacturer': json['bodyManufacturer'] == null ? undefined : json['bodyManufacturer'],
        'bodyModel': json['bodyModel'] == null ? undefined : json['bodyModel'],
        'axesNumber': json['axesNumber'] == null ? undefined : json['axesNumber'],
        'engineDescription': json['engineDescription'] == null ? undefined : json['engineDescription'],
        'hasBathroom': json['hasBathroom'],
        'status': json['status'],
    };
}

export function CreateVehicleRequestToJSON(json: any): CreateVehicleRequest {
    return CreateVehicleRequestToJSONTyped(json, false);
}

export function CreateVehicleRequestToJSONTyped(value?: CreateVehicleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'licensePlate': value['licensePlate'],
        'model': value['model'],
        'vehicleManufacturer': value['vehicleManufacturer'],
        'modelYear': value['modelYear'],
        'manufacturerYear': value['manufacturerYear'],
        'renavan': value['renavan'],
        'passengerNumber': value['passengerNumber'],
        'motorNumber': value['motorNumber'],
        'chassisNumber': value['chassisNumber'],
        'fleetNumber': value['fleetNumber'],
        'fuelTankCapacity': value['fuelTankCapacity'],
        'entryMileage': value['entryMileage'],
        'averageConsumption': value['averageConsumption'],
        'bodyManufacturer': value['bodyManufacturer'],
        'bodyModel': value['bodyModel'],
        'axesNumber': value['axesNumber'],
        'engineDescription': value['engineDescription'],
        'hasBathroom': value['hasBathroom'],
        'status': value['status'],
    };
}

