/* tslint:disable */
/* eslint-disable */
/**
 * Travel Manager - API de Gestão de recursos de transporte rodoviário
 * Especificação modular da API de back-end. Todos os schemas e paths estão em ficheiros separados (specs/). Use um agregador OpenAPI (como o ReDoc ou Swagger UI) para visualizar a documentação completa.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ferdxavier@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ValidationErrorDetail } from './ValidationErrorDetail';
import {
    ValidationErrorDetailFromJSON,
    ValidationErrorDetailFromJSONTyped,
    ValidationErrorDetailToJSON,
    ValidationErrorDetailToJSONTyped,
} from './ValidationErrorDetail';

/**
 * Representa a resposta padrão de erro da API.
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {
    /**
     * Data e hora em que o erro ocorreu.
     * @type {Date}
     * @memberof ErrorResponse
     */
    timestamp: Date;
    /**
     * Código de status HTTP (e.g., 400, 404).
     * @type {number}
     * @memberof ErrorResponse
     */
    status: number;
    /**
     * Código de erro de negócio específico (e.g., 'VEHICLE_ALREADY_EXISTS', 'INVALID_PLATE_FORMAT').
     * @type {string}
     * @memberof ErrorResponse
     */
    errorCode: string;
    /**
     * Mensagem de erro legível e concisa para o desenvolvedor ou usuário.
     * @type {string}
     * @memberof ErrorResponse
     */
    message: string;
    /**
     * ID de rastreamento (trace ID) para correlacionar o erro com os logs do servidor.
     * @type {string}
     * @memberof ErrorResponse
     */
    traceId?: string;
    /**
     * Detalhes adicionais, normalmente usados para erros de validação de campo (400).
     * @type {Array<ValidationErrorDetail>}
     * @memberof ErrorResponse
     */
    details?: Array<ValidationErrorDetail>;
}

/**
 * Check if a given object implements the ErrorResponse interface.
 */
export function instanceOfErrorResponse(value: object): value is ErrorResponse {
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('errorCode' in value) || value['errorCode'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ErrorResponseFromJSON(json: any): ErrorResponse {
    return ErrorResponseFromJSONTyped(json, false);
}

export function ErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'timestamp': (new Date(json['timestamp'])),
        'status': json['status'],
        'errorCode': json['errorCode'],
        'message': json['message'],
        'traceId': json['traceId'] == null ? undefined : json['traceId'],
        'details': json['details'] == null ? undefined : ((json['details'] as Array<any>).map(ValidationErrorDetailFromJSON)),
    };
}

export function ErrorResponseToJSON(json: any): ErrorResponse {
    return ErrorResponseToJSONTyped(json, false);
}

export function ErrorResponseToJSONTyped(value?: ErrorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timestamp': value['timestamp'].toISOString(),
        'status': value['status'],
        'errorCode': value['errorCode'],
        'message': value['message'],
        'traceId': value['traceId'],
        'details': value['details'] == null ? undefined : ((value['details'] as Array<any>).map(ValidationErrorDetailToJSON)),
    };
}

