/* tslint:disable */
/* eslint-disable */
/**
 * Travel Manager - API de Gestão de recursos de transporte rodoviário
 * Especificação modular da API de back-end. Todos os schemas e paths estão em ficheiros separados (specs/). Use um agregador OpenAPI (como o ReDoc ou Swagger UI) para visualizar a documentação completa.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ferdxavier@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Impacto imediato no veículo: bloqueante (impede uso) ou não-bloqueante.
 * @export
 */
export const Impact = {
    Blocking: 'blocking',
    Necessary: 'necessary',
    NonCritical: 'non_critical'
} as const;
export type Impact = typeof Impact[keyof typeof Impact];


export function instanceOfImpact(value: any): boolean {
    for (const key in Impact) {
        if (Object.prototype.hasOwnProperty.call(Impact, key)) {
            if (Impact[key as keyof typeof Impact] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ImpactFromJSON(json: any): Impact {
    return ImpactFromJSONTyped(json, false);
}

export function ImpactFromJSONTyped(json: any, ignoreDiscriminator: boolean): Impact {
    return json as Impact;
}

export function ImpactToJSON(value?: Impact | null): any {
    return value as any;
}

export function ImpactToJSONTyped(value: any, ignoreDiscriminator: boolean): Impact {
    return value as Impact;
}

