/* tslint:disable */
/* eslint-disable */
/**
 * Travel Manager - API de Gestão de recursos de transporte rodoviário
 * Especificação modular da API de back-end. Todos os schemas e paths estão em ficheiros separados (specs/). Use um agregador OpenAPI (como o ReDoc ou Swagger UI) para visualizar a documentação completa.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ferdxavier@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Motivo principal do relato fornecido pelo passageiro.
 * @export
 */
export const PassengerReportReason = {
    DrivingBehavior: 'DrivingBehavior',
    Hygiene: 'hygiene',
    Defect: 'defect',
    Comfort: 'comfort',
    Other: 'other'
} as const;
export type PassengerReportReason = typeof PassengerReportReason[keyof typeof PassengerReportReason];


export function instanceOfPassengerReportReason(value: any): boolean {
    for (const key in PassengerReportReason) {
        if (Object.prototype.hasOwnProperty.call(PassengerReportReason, key)) {
            if (PassengerReportReason[key as keyof typeof PassengerReportReason] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PassengerReportReasonFromJSON(json: any): PassengerReportReason {
    return PassengerReportReasonFromJSONTyped(json, false);
}

export function PassengerReportReasonFromJSONTyped(json: any, ignoreDiscriminator: boolean): PassengerReportReason {
    return json as PassengerReportReason;
}

export function PassengerReportReasonToJSON(value?: PassengerReportReason | null): any {
    return value as any;
}

export function PassengerReportReasonToJSONTyped(value: any, ignoreDiscriminator: boolean): PassengerReportReason {
    return value as PassengerReportReason;
}

