/* tslint:disable */
/* eslint-disable */
/**
 * Travel Manager - API de Gestão de recursos de transporte rodoviário
 * Especificação modular da API de back-end. Todos os schemas e paths estão em ficheiros separados (specs/). Use um agregador OpenAPI (como o ReDoc ou Swagger UI) para visualizar a documentação completa.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ferdxavier@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Prioridade atribuída à ordem de serviço (afeta o SLA).
 * @export
 */
export const Priority = {
    Low: 'low',
    Medium: 'medium',
    High: 'high',
    Critical: 'critical'
} as const;
export type Priority = typeof Priority[keyof typeof Priority];


export function instanceOfPriority(value: any): boolean {
    for (const key in Priority) {
        if (Object.prototype.hasOwnProperty.call(Priority, key)) {
            if (Priority[key as keyof typeof Priority] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PriorityFromJSON(json: any): Priority {
    return PriorityFromJSONTyped(json, false);
}

export function PriorityFromJSONTyped(json: any, ignoreDiscriminator: boolean): Priority {
    return json as Priority;
}

export function PriorityToJSON(value?: Priority | null): any {
    return value as any;
}

export function PriorityToJSONTyped(value: any, ignoreDiscriminator: boolean): Priority {
    return value as Priority;
}

