/* tslint:disable */
/* eslint-disable */
/**
 * Travel Manager - API de Gestão de recursos de transporte rodoviário
 * Especificação modular da API de back-end. Todos os schemas e paths estão em ficheiros separados (specs/). Use um agregador OpenAPI (como o ReDoc ou Swagger UI) para visualizar a documentação completa.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ferdxavier@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Tipo de manutenção: interna (frota própria) ou externa (terceirizada).
 * @export
 */
export const Type = {
    Internal: 'internal',
    External: 'external'
} as const;
export type Type = typeof Type[keyof typeof Type];


export function instanceOfType(value: any): boolean {
    for (const key in Type) {
        if (Object.prototype.hasOwnProperty.call(Type, key)) {
            if (Type[key as keyof typeof Type] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TypeFromJSON(json: any): Type {
    return TypeFromJSONTyped(json, false);
}

export function TypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Type {
    return json as Type;
}

export function TypeToJSON(value?: Type | null): any {
    return value as any;
}

export function TypeToJSONTyped(value: any, ignoreDiscriminator: boolean): Type {
    return value as Type;
}

