/* tslint:disable */
/* eslint-disable */
/**
 * Travel Manager - API de Gestão de recursos de transporte rodoviário
 * Especificação modular da API de back-end. Todos os schemas e paths estão em ficheiros separados (specs/). Use um agregador OpenAPI (como o ReDoc ou Swagger UI) para visualizar a documentação completa.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ferdxavier@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Detalhes de falha de validação em um campo específico.
 * @export
 * @interface ValidationErrorDetail
 */
export interface ValidationErrorDetail {
    /**
     * Nome do campo que falhou na validação.
     * @type {string}
     * @memberof ValidationErrorDetail
     */
    field?: string;
    /**
     * Descrição do problema de validação (e.g., 'must be a positive number', 'is required').
     * @type {string}
     * @memberof ValidationErrorDetail
     */
    issue?: string;
    /**
     * O valor alvo do opração que gerou o erro caso exista.
     * @type {string}
     * @memberof ValidationErrorDetail
     */
    targetValue?: string;
}

/**
 * Check if a given object implements the ValidationErrorDetail interface.
 */
export function instanceOfValidationErrorDetail(value: object): value is ValidationErrorDetail {
    return true;
}

export function ValidationErrorDetailFromJSON(json: any): ValidationErrorDetail {
    return ValidationErrorDetailFromJSONTyped(json, false);
}

export function ValidationErrorDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidationErrorDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'field': json['field'] == null ? undefined : json['field'],
        'issue': json['issue'] == null ? undefined : json['issue'],
        'targetValue': json['targetValue'] == null ? undefined : json['targetValue'],
    };
}

export function ValidationErrorDetailToJSON(json: any): ValidationErrorDetail {
    return ValidationErrorDetailToJSONTyped(json, false);
}

export function ValidationErrorDetailToJSONTyped(value?: ValidationErrorDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'field': value['field'],
        'issue': value['issue'],
        'targetValue': value['targetValue'],
    };
}

