/* tslint:disable */
/* eslint-disable */
/**
 * Travel Manager - API de Gestão de recursos de transporte rodoviário
 * Especificação modular da API de back-end. Todos os schemas e paths estão em ficheiros separados (specs/). Use um agregador OpenAPI (como o ReDoc ou Swagger UI) para visualizar a documentação completa.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ferdxavier@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VehicleCommonProperties
 */
export interface VehicleCommonProperties {
    /**
     * Placa do veículo. Formato Mercosul (LLLNLNN).
     * @type {string}
     * @memberof VehicleCommonProperties
     */
    licensePlate?: string;
    /**
     * Modelo e nome do veículo.
     * @type {string}
     * @memberof VehicleCommonProperties
     */
    model?: string;
    /**
     * Fabricante do veículo.
     * @type {string}
     * @memberof VehicleCommonProperties
     */
    vehicleManufacturer?: string;
    /**
     * Ano do Modelo do veículo.
     * @type {number}
     * @memberof VehicleCommonProperties
     */
    modelYear?: number;
    /**
     * Ano de fabricação do veículo.
     * @type {number}
     * @memberof VehicleCommonProperties
     */
    manufacturerYear?: number;
    /**
     * Número do RENAVAN do veículo.
     * @type {string}
     * @memberof VehicleCommonProperties
     */
    renavan?: string;
    /**
     * Em caso de veículo de transporte, o número de passageiros.
     * @type {number}
     * @memberof VehicleCommonProperties
     */
    passengerNumber?: number;
    /**
     * Número do motor do veículo.
     * @type {string}
     * @memberof VehicleCommonProperties
     */
    motorNumber?: string;
    /**
     * Número do chassis do veículo.
     * @type {string}
     * @memberof VehicleCommonProperties
     */
    chassisNumber?: string;
    /**
     * Número interno que corresponte ao id do veículo da frota da empresa.
     * @type {number}
     * @memberof VehicleCommonProperties
     */
    fleetNumber?: number;
    /**
     * Capacidade do tanque de combustivel do veículo.
     * @type {number}
     * @memberof VehicleCommonProperties
     */
    fuelTankCapacity?: number;
    /**
     * Quilometragem do veículo na entrada da empresa (no cadastro).
     * @type {number}
     * @memberof VehicleCommonProperties
     */
    entryMileage?: number;
    /**
     * Média de Quilômetros por litro de conbustivel.
     * @type {number}
     * @memberof VehicleCommonProperties
     */
    averageConsumption?: number;
    /**
     * Fabricante da carroceria.
     * @type {string}
     * @memberof VehicleCommonProperties
     */
    bodyManufacturer?: string;
    /**
     * Nome do modelo da carroceria.
     * @type {string}
     * @memberof VehicleCommonProperties
     */
    bodyModel?: string;
    /**
     * Número de eixos que o veículo possui.
     * @type {number}
     * @memberof VehicleCommonProperties
     */
    axesNumber?: number;
    /**
     * Descrição do motor.
     * @type {string}
     * @memberof VehicleCommonProperties
     */
    engineDescription?: string;
    /**
     * Se o veículo possui banheiro
     * @type {boolean}
     * @memberof VehicleCommonProperties
     */
    hasBathroom?: boolean;
    /**
     * Status operacional atual/desejado do veículo.
     * @type {string}
     * @memberof VehicleCommonProperties
     */
    status?: VehicleCommonPropertiesStatusEnum;
}


/**
 * @export
 */
export const VehicleCommonPropertiesStatusEnum = {
    Available: 'available',
    Maintenance: 'maintenance',
    Retired: 'retired'
} as const;
export type VehicleCommonPropertiesStatusEnum = typeof VehicleCommonPropertiesStatusEnum[keyof typeof VehicleCommonPropertiesStatusEnum];


/**
 * Check if a given object implements the VehicleCommonProperties interface.
 */
export function instanceOfVehicleCommonProperties(value: object): value is VehicleCommonProperties {
    return true;
}

export function VehicleCommonPropertiesFromJSON(json: any): VehicleCommonProperties {
    return VehicleCommonPropertiesFromJSONTyped(json, false);
}

export function VehicleCommonPropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): VehicleCommonProperties {
    if (json == null) {
        return json;
    }
    return {
        
        'licensePlate': json['licensePlate'] == null ? undefined : json['licensePlate'],
        'model': json['model'] == null ? undefined : json['model'],
        'vehicleManufacturer': json['vehicleManufacturer'] == null ? undefined : json['vehicleManufacturer'],
        'modelYear': json['modelYear'] == null ? undefined : json['modelYear'],
        'manufacturerYear': json['manufacturerYear'] == null ? undefined : json['manufacturerYear'],
        'renavan': json['renavan'] == null ? undefined : json['renavan'],
        'passengerNumber': json['passengerNumber'] == null ? undefined : json['passengerNumber'],
        'motorNumber': json['motorNumber'] == null ? undefined : json['motorNumber'],
        'chassisNumber': json['chassisNumber'] == null ? undefined : json['chassisNumber'],
        'fleetNumber': json['fleetNumber'] == null ? undefined : json['fleetNumber'],
        'fuelTankCapacity': json['fuelTankCapacity'] == null ? undefined : json['fuelTankCapacity'],
        'entryMileage': json['entryMileage'] == null ? undefined : json['entryMileage'],
        'averageConsumption': json['averageConsumption'] == null ? undefined : json['averageConsumption'],
        'bodyManufacturer': json['bodyManufacturer'] == null ? undefined : json['bodyManufacturer'],
        'bodyModel': json['bodyModel'] == null ? undefined : json['bodyModel'],
        'axesNumber': json['axesNumber'] == null ? undefined : json['axesNumber'],
        'engineDescription': json['engineDescription'] == null ? undefined : json['engineDescription'],
        'hasBathroom': json['hasBathroom'] == null ? undefined : json['hasBathroom'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function VehicleCommonPropertiesToJSON(json: any): VehicleCommonProperties {
    return VehicleCommonPropertiesToJSONTyped(json, false);
}

export function VehicleCommonPropertiesToJSONTyped(value?: VehicleCommonProperties | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'licensePlate': value['licensePlate'],
        'model': value['model'],
        'vehicleManufacturer': value['vehicleManufacturer'],
        'modelYear': value['modelYear'],
        'manufacturerYear': value['manufacturerYear'],
        'renavan': value['renavan'],
        'passengerNumber': value['passengerNumber'],
        'motorNumber': value['motorNumber'],
        'chassisNumber': value['chassisNumber'],
        'fleetNumber': value['fleetNumber'],
        'fuelTankCapacity': value['fuelTankCapacity'],
        'entryMileage': value['entryMileage'],
        'averageConsumption': value['averageConsumption'],
        'bodyManufacturer': value['bodyManufacturer'],
        'bodyModel': value['bodyModel'],
        'axesNumber': value['axesNumber'],
        'engineDescription': value['engineDescription'],
        'hasBathroom': value['hasBathroom'],
        'status': value['status'],
    };
}

