/* tslint:disable */
/* eslint-disable */
/**
 * Travel Manager - API de Gestão de recursos de transporte rodoviário
 * Especificação modular da API de back-end. Todos os schemas e paths estão em ficheiros separados (specs/). Use um agregador OpenAPI (como o ReDoc ou Swagger UI) para visualizar a documentação completa.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ferdxavier@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Representação completa de um veículo na frota.
 * @export
 * @interface Vehicle
 */
export interface Vehicle {
    /**
     * ID único gerado pelo sistema.
     * @type {string}
     * @memberof Vehicle
     */
    id: string;
    /**
     * Timestamp de criação do registro.
     * @type {Date}
     * @memberof Vehicle
     */
    createdAt?: Date;
    /**
     * Placa do veículo. Formato Mercosul (LLLNLNN).
     * @type {string}
     * @memberof Vehicle
     */
    licensePlate: string;
    /**
     * Modelo e nome do veículo.
     * @type {string}
     * @memberof Vehicle
     */
    model: string;
    /**
     * Fabricante do veículo.
     * @type {string}
     * @memberof Vehicle
     */
    vehicleManufacturer?: string;
    /**
     * Ano do Modelo do veículo.
     * @type {number}
     * @memberof Vehicle
     */
    modelYear?: number;
    /**
     * Ano de fabricação do veículo.
     * @type {number}
     * @memberof Vehicle
     */
    manufacturerYear?: number;
    /**
     * Número do RENAVAN do veículo.
     * @type {string}
     * @memberof Vehicle
     */
    renavan?: string;
    /**
     * Em caso de veículo de transporte, o número de passageiros.
     * @type {number}
     * @memberof Vehicle
     */
    passengerNumber?: number;
    /**
     * Número do motor do veículo.
     * @type {string}
     * @memberof Vehicle
     */
    motorNumber?: string;
    /**
     * Número do chassis do veículo.
     * @type {string}
     * @memberof Vehicle
     */
    chassisNumber?: string;
    /**
     * Número interno que corresponte ao id do veículo da frota da empresa.
     * @type {number}
     * @memberof Vehicle
     */
    fleetNumber?: number;
    /**
     * Capacidade do tanque de combustivel do veículo.
     * @type {number}
     * @memberof Vehicle
     */
    fuelTankCapacity?: number;
    /**
     * Quilometragem do veículo na entrada da empresa (no cadastro).
     * @type {number}
     * @memberof Vehicle
     */
    entryMileage?: number;
    /**
     * Média de Quilômetros por litro de conbustivel.
     * @type {number}
     * @memberof Vehicle
     */
    averageConsumption?: number;
    /**
     * Fabricante da carroceria.
     * @type {string}
     * @memberof Vehicle
     */
    bodyManufacturer?: string;
    /**
     * Nome do modelo da carroceria.
     * @type {string}
     * @memberof Vehicle
     */
    bodyModel?: string;
    /**
     * Número de eixos que o veículo possui.
     * @type {number}
     * @memberof Vehicle
     */
    axesNumber?: number;
    /**
     * Descrição do motor.
     * @type {string}
     * @memberof Vehicle
     */
    engineDescription?: string;
    /**
     * Se o veículo possui banheiro
     * @type {boolean}
     * @memberof Vehicle
     */
    hasBathroom?: boolean;
    /**
     * Status operacional atual/desejado do veículo.
     * @type {string}
     * @memberof Vehicle
     */
    status: VehicleStatusEnum;
}


/**
 * @export
 */
export const VehicleStatusEnum = {
    Available: 'available',
    Maintenance: 'maintenance',
    Retired: 'retired'
} as const;
export type VehicleStatusEnum = typeof VehicleStatusEnum[keyof typeof VehicleStatusEnum];


/**
 * Check if a given object implements the Vehicle interface.
 */
export function instanceOfVehicle(value: object): value is Vehicle {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('licensePlate' in value) || value['licensePlate'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function VehicleFromJSON(json: any): Vehicle {
    return VehicleFromJSONTyped(json, false);
}

export function VehicleFromJSONTyped(json: any, ignoreDiscriminator: boolean): Vehicle {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'licensePlate': json['licensePlate'],
        'model': json['model'],
        'vehicleManufacturer': json['vehicleManufacturer'] == null ? undefined : json['vehicleManufacturer'],
        'modelYear': json['modelYear'] == null ? undefined : json['modelYear'],
        'manufacturerYear': json['manufacturerYear'] == null ? undefined : json['manufacturerYear'],
        'renavan': json['renavan'] == null ? undefined : json['renavan'],
        'passengerNumber': json['passengerNumber'] == null ? undefined : json['passengerNumber'],
        'motorNumber': json['motorNumber'] == null ? undefined : json['motorNumber'],
        'chassisNumber': json['chassisNumber'] == null ? undefined : json['chassisNumber'],
        'fleetNumber': json['fleetNumber'] == null ? undefined : json['fleetNumber'],
        'fuelTankCapacity': json['fuelTankCapacity'] == null ? undefined : json['fuelTankCapacity'],
        'entryMileage': json['entryMileage'] == null ? undefined : json['entryMileage'],
        'averageConsumption': json['averageConsumption'] == null ? undefined : json['averageConsumption'],
        'bodyManufacturer': json['bodyManufacturer'] == null ? undefined : json['bodyManufacturer'],
        'bodyModel': json['bodyModel'] == null ? undefined : json['bodyModel'],
        'axesNumber': json['axesNumber'] == null ? undefined : json['axesNumber'],
        'engineDescription': json['engineDescription'] == null ? undefined : json['engineDescription'],
        'hasBathroom': json['hasBathroom'] == null ? undefined : json['hasBathroom'],
        'status': json['status'],
    };
}

export function VehicleToJSON(json: any): Vehicle {
    return VehicleToJSONTyped(json, false);
}

export function VehicleToJSONTyped(value?: Vehicle | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'licensePlate': value['licensePlate'],
        'model': value['model'],
        'vehicleManufacturer': value['vehicleManufacturer'],
        'modelYear': value['modelYear'],
        'manufacturerYear': value['manufacturerYear'],
        'renavan': value['renavan'],
        'passengerNumber': value['passengerNumber'],
        'motorNumber': value['motorNumber'],
        'chassisNumber': value['chassisNumber'],
        'fleetNumber': value['fleetNumber'],
        'fuelTankCapacity': value['fuelTankCapacity'],
        'entryMileage': value['entryMileage'],
        'averageConsumption': value['averageConsumption'],
        'bodyManufacturer': value['bodyManufacturer'],
        'bodyModel': value['bodyModel'],
        'axesNumber': value['axesNumber'],
        'engineDescription': value['engineDescription'],
        'hasBathroom': value['hasBathroom'],
        'status': value['status'],
    };
}

