/* tslint:disable */
/* eslint-disable */
/**
 * Travel Manager - API de Gestão de recursos de transporte rodoviário
 * Especificação modular da API de back-end. Todos os schemas e paths estão em ficheiros separados (specs/). Use um agregador OpenAPI (como o ReDoc ou Swagger UI) para visualizar a documentação completa.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ferdxavier@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateDriverRequest,
  Driver,
  ErrorResponse,
} from '../models/index';
import {
    CreateDriverRequestFromJSON,
    CreateDriverRequestToJSON,
    DriverFromJSON,
    DriverToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/index';

export interface CreateDriverOperationRequest {
    createDriverRequest: CreateDriverRequest;
}

export interface ListDriversRequest {
    limit?: number;
    offset?: number;
}

/**
 * 
 */
export class DriversApi extends runtime.BaseAPI {

    /**
     * Registra um novo motorista.
     * Cria um novo motorista no sistema.
     */
    async createDriverRaw(requestParameters: CreateDriverOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Driver>> {
        if (requestParameters['createDriverRequest'] == null) {
            throw new runtime.RequiredError(
                'createDriverRequest',
                'Required parameter "createDriverRequest" was null or undefined when calling createDriver().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/drivers`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateDriverRequestToJSON(requestParameters['createDriverRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DriverFromJSON(jsonValue));
    }

    /**
     * Registra um novo motorista.
     * Cria um novo motorista no sistema.
     */
    async createDriver(requestParameters: CreateDriverOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Driver> {
        const response = await this.createDriverRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Recupera uma lista paginada de todos os motoristas registados na empresa.
     * Lista todos os motoristas da empresa.
     */
    async listDriversRaw(requestParameters: ListDriversRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Driver>>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/drivers`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DriverFromJSON));
    }

    /**
     * Recupera uma lista paginada de todos os motoristas registados na empresa.
     * Lista todos os motoristas da empresa.
     */
    async listDrivers(requestParameters: ListDriversRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Driver>> {
        const response = await this.listDriversRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
