/* tslint:disable */
/* eslint-disable */
/**
 * Travel Manager - API de Gestão de recursos de transporte rodoviário
 * Especificação modular da API de back-end. Todos os schemas e paths estão em ficheiros separados (specs/). Use um agregador OpenAPI (como o ReDoc ou Swagger UI) para visualizar a documentação completa.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ferdxavier@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreatePassengerReportRequest,
  ErrorResponse,
} from '../models/index';
import {
    CreatePassengerReportRequestFromJSON,
    CreatePassengerReportRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/index';

export interface CreatePassengerReportOperationRequest {
    createPassengerReportRequest: CreatePassengerReportRequest;
}

/**
 * 
 */
export class PassengerReportsApi extends runtime.BaseAPI {

    /**
     * Recebe os dados básicos e anónimos de um passageiro sobre um problema no veículo. O *backend* processará esta informação (triagem) e decidirá se uma Ordem de Serviço será criada com base nos requisitos atendidos. 
     * Cria um novo relato anónimo de problema por um passageiro.
     */
    async createPassengerReportRaw(requestParameters: CreatePassengerReportOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['createPassengerReportRequest'] == null) {
            throw new runtime.RequiredError(
                'createPassengerReportRequest',
                'Required parameter "createPassengerReportRequest" was null or undefined when calling createPassengerReport().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/reportReason/passenger`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePassengerReportRequestToJSON(requestParameters['createPassengerReportRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Recebe os dados básicos e anónimos de um passageiro sobre um problema no veículo. O *backend* processará esta informação (triagem) e decidirá se uma Ordem de Serviço será criada com base nos requisitos atendidos. 
     * Cria um novo relato anónimo de problema por um passageiro.
     */
    async createPassengerReport(requestParameters: CreatePassengerReportOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createPassengerReportRaw(requestParameters, initOverrides);
    }

}
