/* tslint:disable */
/* eslint-disable */
/**
 * Travel Manager - API de Gestão de recursos de transporte rodoviário
 * Especificação modular da API de back-end. Todos os schemas e paths estão em ficheiros separados (specs/). Use um agregador OpenAPI (como o ReDoc ou Swagger UI) para visualizar a documentação completa.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ferdxavier@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateDriverReportRequest,
  ErrorResponse,
} from '../models/index';
import {
    CreateDriverReportRequestFromJSON,
    CreateDriverReportRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/index';

export interface CreateDriverReportOperationRequest {
    createDriverReportRequest: CreateDriverReportRequest;
}

/**
 * 
 */
export class ReportReasonApi extends runtime.BaseAPI {

    /**
     * Recebe os dados granulares de um motorista sobre um problema no veículo. O *backend* processará esta informação (triagem) e decidirá se uma Ordem de Serviço será criada com base nos requisitos atendidos. 
     * Cria um novo relato detalhado de problema por um motorista.
     */
    async createDriverReportRaw(requestParameters: CreateDriverReportOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['createDriverReportRequest'] == null) {
            throw new runtime.RequiredError(
                'createDriverReportRequest',
                'Required parameter "createDriverReportRequest" was null or undefined when calling createDriverReport().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/reportReason/driver`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateDriverReportRequestToJSON(requestParameters['createDriverReportRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Recebe os dados granulares de um motorista sobre um problema no veículo. O *backend* processará esta informação (triagem) e decidirá se uma Ordem de Serviço será criada com base nos requisitos atendidos. 
     * Cria um novo relato detalhado de problema por um motorista.
     */
    async createDriverReport(requestParameters: CreateDriverReportOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createDriverReportRaw(requestParameters, initOverrides);
    }

}
