/* tslint:disable */
/* eslint-disable */
/**
 * Travel Manager - API de Gestão de recursos de transporte rodoviário
 * Especificação modular da API de back-end. Todos os schemas e paths estão em ficheiros separados (specs/). Use um agregador OpenAPI (como o ReDoc ou Swagger UI) para visualizar a documentação completa.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ferdxavier@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateServiceOrdersRequest,
  ErrorResponse,
  ServiceOrders,
} from '../models/index';
import {
    CreateServiceOrdersRequestFromJSON,
    CreateServiceOrdersRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ServiceOrdersFromJSON,
    ServiceOrdersToJSON,
} from '../models/index';

export interface DeleteServiceOrderRequest {
    id: string;
}

export interface GetServiceOrderByIdRequest {
    id: string;
}

export interface ReplaceServiceOrderRequest {
    id: string;
    createServiceOrdersRequest: CreateServiceOrdersRequest;
}

export interface UpdateServiceOrderRequest {
    id: string;
    createServiceOrdersRequest: CreateServiceOrdersRequest;
}

/**
 * 
 */
export class ServiceOrdersApi extends runtime.BaseAPI {

    /**
     * Remove permanentemente uma Ordem de Serviço pelo seu ID.
     * Remove uma Ordem de Serviço.
     */
    async deleteServiceOrderRaw(requestParameters: DeleteServiceOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteServiceOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/serviceOrders/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remove permanentemente uma Ordem de Serviço pelo seu ID.
     * Remove uma Ordem de Serviço.
     */
    async deleteServiceOrder(requestParameters: DeleteServiceOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteServiceOrderRaw(requestParameters, initOverrides);
    }

    /**
     * Retorna a representação completa de uma Ordem de Serviço pelo seu ID único.
     * Recupera os detalhes de uma Ordem de Serviço específica.
     */
    async getServiceOrderByIdRaw(requestParameters: GetServiceOrderByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServiceOrders>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getServiceOrderById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/serviceOrders/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServiceOrdersFromJSON(jsonValue));
    }

    /**
     * Retorna a representação completa de uma Ordem de Serviço pelo seu ID único.
     * Recupera os detalhes de uma Ordem de Serviço específica.
     */
    async getServiceOrderById(requestParameters: GetServiceOrderByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServiceOrders> {
        const response = await this.getServiceOrderByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Substitui o registo completo. Requer todos os campos obrigatórios.
     * Substitui completamente um registo de Ordem de Serviço.
     */
    async replaceServiceOrderRaw(requestParameters: ReplaceServiceOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServiceOrders>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling replaceServiceOrder().'
            );
        }

        if (requestParameters['createServiceOrdersRequest'] == null) {
            throw new runtime.RequiredError(
                'createServiceOrdersRequest',
                'Required parameter "createServiceOrdersRequest" was null or undefined when calling replaceServiceOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/serviceOrders/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CreateServiceOrdersRequestToJSON(requestParameters['createServiceOrdersRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServiceOrdersFromJSON(jsonValue));
    }

    /**
     * Substitui o registo completo. Requer todos os campos obrigatórios.
     * Substitui completamente um registo de Ordem de Serviço.
     */
    async replaceServiceOrder(requestParameters: ReplaceServiceOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServiceOrders> {
        const response = await this.replaceServiceOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Permite atualizar um ou mais campos (Partial Update).
     * Atualiza parcialmente os detalhes de uma Ordem de Serviço.
     */
    async updateServiceOrderRaw(requestParameters: UpdateServiceOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServiceOrders>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateServiceOrder().'
            );
        }

        if (requestParameters['createServiceOrdersRequest'] == null) {
            throw new runtime.RequiredError(
                'createServiceOrdersRequest',
                'Required parameter "createServiceOrdersRequest" was null or undefined when calling updateServiceOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/serviceOrders/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: CreateServiceOrdersRequestToJSON(requestParameters['createServiceOrdersRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServiceOrdersFromJSON(jsonValue));
    }

    /**
     * Permite atualizar um ou mais campos (Partial Update).
     * Atualiza parcialmente os detalhes de uma Ordem de Serviço.
     */
    async updateServiceOrder(requestParameters: UpdateServiceOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServiceOrders> {
        const response = await this.updateServiceOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
