/* tslint:disable */
/* eslint-disable */
/**
 * Travel Manager - API de Gestão de recursos de transporte rodoviário
 * Especificação modular da API de back-end. Todos os schemas e paths estão em ficheiros separados (specs/). Use um agregador OpenAPI (como o ReDoc ou Swagger UI) para visualizar a documentação completa.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ferdxavier@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateVehicleRequest,
  UpdateVehicleRequest,
  Vehicle,
} from '../models/index';
import {
    CreateVehicleRequestFromJSON,
    CreateVehicleRequestToJSON,
    UpdateVehicleRequestFromJSON,
    UpdateVehicleRequestToJSON,
    VehicleFromJSON,
    VehicleToJSON,
} from '../models/index';

export interface CreateVehicleOperationRequest {
    createVehicleRequest: CreateVehicleRequest;
}

export interface DeleteVehicleRequest {
    id: number;
}

export interface GetVehicleByIdRequest {
    id: number;
}

export interface ListVehiclesRequest {
    status?: ListVehiclesStatusEnum;
    limit?: number;
}

export interface ReplaceVehicleRequest {
    id: number;
    createVehicleRequest: CreateVehicleRequest;
}

export interface UpdateVehicleOperationRequest {
    id: number;
    updateVehicleRequest: UpdateVehicleRequest;
}

/**
 * 
 */
export class VehiclesApi extends runtime.BaseAPI {

    /**
     * Adiciona um novo veículo à frota, validando que a placa de matrícula é única.
     * Cria um novo registo de veículo na frota.
     */
    async createVehicleRaw(requestParameters: CreateVehicleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Vehicle>> {
        if (requestParameters['createVehicleRequest'] == null) {
            throw new runtime.RequiredError(
                'createVehicleRequest',
                'Required parameter "createVehicleRequest" was null or undefined when calling createVehicle().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", ["kjshdfahskfhakjsdfhkjasdhfkadsh"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/vehicles`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateVehicleRequestToJSON(requestParameters['createVehicleRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VehicleFromJSON(jsonValue));
    }

    /**
     * Adiciona um novo veículo à frota, validando que a placa de matrícula é única.
     * Cria um novo registo de veículo na frota.
     */
    async createVehicle(requestParameters: CreateVehicleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Vehicle> {
        const response = await this.createVehicleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Remove permanentemente (ou logicamente desativa) um veículo pelo seu ID.
     * Remove um veículo da frota.
     */
    async deleteVehicleRaw(requestParameters: DeleteVehicleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteVehicle().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", ["kjshdfahskfhakjsdfhkjasdhfkadsh"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/vehicles/{id}`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remove permanentemente (ou logicamente desativa) um veículo pelo seu ID.
     * Remove um veículo da frota.
     */
    async deleteVehicle(requestParameters: DeleteVehicleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteVehicleRaw(requestParameters, initOverrides);
    }

    /**
     * Retorna a representação completa de um veículo pelo seu ID único.
     * Recupera os detalhes de um veículo específico.
     */
    async getVehicleByIdRaw(requestParameters: GetVehicleByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Vehicle>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getVehicleById().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", ["kjshdfahskfhakjsdfhkjasdhfkadsh"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/vehicles/{id}`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VehicleFromJSON(jsonValue));
    }

    /**
     * Retorna a representação completa de um veículo pelo seu ID único.
     * Recupera os detalhes de um veículo específico.
     */
    async getVehicleById(requestParameters: GetVehicleByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Vehicle> {
        const response = await this.getVehicleByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Recupera uma lista paginada de todos os veículos registados na frota, com opções de filtragem por status operacional.
     * Lista todos os veículos disponíveis na frota.
     */
    async listVehiclesRaw(requestParameters: ListVehiclesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Vehicle>>> {
        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", ["kjshdfahskfhakjsdfhkjasdhfkadsh"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/vehicles`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(VehicleFromJSON));
    }

    /**
     * Recupera uma lista paginada de todos os veículos registados na frota, com opções de filtragem por status operacional.
     * Lista todos os veículos disponíveis na frota.
     */
    async listVehicles(requestParameters: ListVehiclesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Vehicle>> {
        const response = await this.listVehiclesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Substitui o registo completo do veículo pelo ID. Requer todos os campos obrigatórios.
     * Substitui completamente um registo de veículo.
     */
    async replaceVehicleRaw(requestParameters: ReplaceVehicleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Vehicle>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling replaceVehicle().'
            );
        }

        if (requestParameters['createVehicleRequest'] == null) {
            throw new runtime.RequiredError(
                'createVehicleRequest',
                'Required parameter "createVehicleRequest" was null or undefined when calling replaceVehicle().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", ["kjshdfahskfhakjsdfhkjasdhfkadsh"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/vehicles/{id}`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CreateVehicleRequestToJSON(requestParameters['createVehicleRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VehicleFromJSON(jsonValue));
    }

    /**
     * Substitui o registo completo do veículo pelo ID. Requer todos os campos obrigatórios.
     * Substitui completamente um registo de veículo.
     */
    async replaceVehicle(requestParameters: ReplaceVehicleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Vehicle> {
        const response = await this.replaceVehicleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Permite atualizar um ou mais campos do veículo sem enviar o objeto completo (Partial Update).
     * Atualiza parcialmente os detalhes de um veículo.
     */
    async updateVehicleRaw(requestParameters: UpdateVehicleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Vehicle>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateVehicle().'
            );
        }

        if (requestParameters['updateVehicleRequest'] == null) {
            throw new runtime.RequiredError(
                'updateVehicleRequest',
                'Required parameter "updateVehicleRequest" was null or undefined when calling updateVehicle().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", ["kjshdfahskfhakjsdfhkjasdhfkadsh"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/vehicles/{id}`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateVehicleRequestToJSON(requestParameters['updateVehicleRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VehicleFromJSON(jsonValue));
    }

    /**
     * Permite atualizar um ou mais campos do veículo sem enviar o objeto completo (Partial Update).
     * Atualiza parcialmente os detalhes de um veículo.
     */
    async updateVehicle(requestParameters: UpdateVehicleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Vehicle> {
        const response = await this.updateVehicleRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ListVehiclesStatusEnum = {
    Available: 'available',
    Maintenance: 'maintenance',
    Retired: 'retired'
} as const;
export type ListVehiclesStatusEnum = typeof ListVehiclesStatusEnum[keyof typeof ListVehiclesStatusEnum];
