/* tslint:disable */
/* eslint-disable */
/**
 * Travel Manager - API de Gestão de recursos de transporte rodoviário
 * Especificação modular da API de back-end. Todos os schemas e paths estão em ficheiros separados (specs/). Use um agregador OpenAPI (como o ReDoc ou Swagger UI) para visualizar a documentação completa.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ferdxavier@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Natureza da manutenção: preventiva (agendada), corretiva (necessária/quebra) ou preditiva (baseada em dados).
 * @export
 */
export const MaintenanceNature = {
    Preventive: 'preventive',
    Corrective: 'corrective',
    Predictive: 'predictive'
} as const;
export type MaintenanceNature = typeof MaintenanceNature[keyof typeof MaintenanceNature];


export function instanceOfMaintenanceNature(value: any): boolean {
    for (const key in MaintenanceNature) {
        if (Object.prototype.hasOwnProperty.call(MaintenanceNature, key)) {
            if (MaintenanceNature[key as keyof typeof MaintenanceNature] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MaintenanceNatureFromJSON(json: any): MaintenanceNature {
    return MaintenanceNatureFromJSONTyped(json, false);
}

export function MaintenanceNatureFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaintenanceNature {
    return json as MaintenanceNature;
}

export function MaintenanceNatureToJSON(value?: MaintenanceNature | null): any {
    return value as any;
}

export function MaintenanceNatureToJSONTyped(value: any, ignoreDiscriminator: boolean): MaintenanceNature {
    return value as MaintenanceNature;
}

