/* tslint:disable */
/* eslint-disable */
/**
 * Travel Manager - API de Gestão de recursos de transporte rodoviário
 * Especificação modular da API de back-end. Todos os schemas e paths estão em ficheiros separados (specs/). Use um agregador OpenAPI (como o ReDoc ou Swagger UI) para visualizar a documentação completa.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ferdxavier@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../../runtime';
/**
 * Representação completa de ordem de serviço para veiculos, com detalhes granulares sobre o tipo e prioridade da manutenção.
 * @export
 * @interface ServiceOrders
 */
export interface ServiceOrders {
    /**
     * ID único gerado pelo sistema.
     * @type {string}
     * @memberof ServiceOrders
     */
    id?: string;
    /**
     * ID do veículo ao qual a ordem de serviço está associada.
     * @type {string}
     * @memberof ServiceOrders
     */
    vehicleId?: string;
    /**
     * ID do usuário que inseriu/criou a ordem de serviço.
     * @type {string}
     * @memberof ServiceOrders
     */
    userId?: string;
    /**
     * Status atual da ordem de serviço.
     * @type {string}
     * @memberof ServiceOrders
     */
    status?: ServiceOrdersStatusEnum;
    /**
     * Tipo de manutenção: interna (frota própria) ou externa (terceirizada).
     * @type {string}
     * @memberof ServiceOrders
     */
    type?: ServiceOrdersTypeEnum;
    /**
     * Categoria da manutenção, focando na área do veículo.
     * @type {string}
     * @memberof ServiceOrders
     */
    category?: ServiceOrdersCategoryEnum;
    /**
     * Natureza da manutenção: preventiva (agendada), corretiva (necessária/quebra) ou preditiva (baseada em dados).
     * @type {string}
     * @memberof ServiceOrders
     */
    maintenanceNature?: ServiceOrdersMaintenanceNatureEnum;
    /**
     * Impacto imediato no veículo: bloqueante (impede uso) ou não-bloqueante.
     * @type {string}
     * @memberof ServiceOrders
     */
    impact?: ServiceOrdersImpactEnum;
    /**
     * Prioridade atribuída à ordem de serviço (afeta o SLA).
     * @type {string}
     * @memberof ServiceOrders
     */
    priority?: ServiceOrdersPriorityEnum;
    /**
     * Descrição detalhada do problema ou serviço a ser realizado.
     * @type {string}
     * @memberof ServiceOrders
     */
    description?: string;
    /**
     * Data em que o serviço foi agendado ou concluído.
     * @type {Date}
     * @memberof ServiceOrders
     */
    serviceDate?: Date | null;
    /**
     * Custo total da ordem de serviço, se aplicável.
     * @type {number}
     * @memberof ServiceOrders
     */
    cost?: number | null;
    /**
     * Carimbo de data/hora da criação do registo.
     * @type {Date}
     * @memberof ServiceOrders
     */
    createdAt?: Date;
}


/**
 * @export
 */
export const ServiceOrdersStatusEnum = {
    Open: 'open',
    InProgress: 'in_progress',
    Closed: 'closed',
    Canceled: 'canceled'
} as const;
export type ServiceOrdersStatusEnum = typeof ServiceOrdersStatusEnum[keyof typeof ServiceOrdersStatusEnum];

/**
 * @export
 */
export const ServiceOrdersTypeEnum = {
    Internal: 'internal',
    External: 'external'
} as const;
export type ServiceOrdersTypeEnum = typeof ServiceOrdersTypeEnum[keyof typeof ServiceOrdersTypeEnum];

/**
 * @export
 */
export const ServiceOrdersCategoryEnum = {
    EngineAndTransmission: 'engine_and_transmission',
    ChassisAndSuspension: 'chassis_and_suspension',
    BodyAndInterior: 'body_and_interior',
    ElectricSystem: 'electric_system',
    TiresAndWheels: 'tires_and_wheels',
    GeneralInspection: 'general_inspection'
} as const;
export type ServiceOrdersCategoryEnum = typeof ServiceOrdersCategoryEnum[keyof typeof ServiceOrdersCategoryEnum];

/**
 * @export
 */
export const ServiceOrdersMaintenanceNatureEnum = {
    Preventive: 'preventive',
    Corrective: 'corrective',
    Predictive: 'predictive'
} as const;
export type ServiceOrdersMaintenanceNatureEnum = typeof ServiceOrdersMaintenanceNatureEnum[keyof typeof ServiceOrdersMaintenanceNatureEnum];

/**
 * @export
 */
export const ServiceOrdersImpactEnum = {
    Blocking: 'blocking',
    Necessary: 'necessary',
    NonCritical: 'non_critical'
} as const;
export type ServiceOrdersImpactEnum = typeof ServiceOrdersImpactEnum[keyof typeof ServiceOrdersImpactEnum];

/**
 * @export
 */
export const ServiceOrdersPriorityEnum = {
    Low: 'low',
    Medium: 'medium',
    High: 'high',
    Critical: 'critical'
} as const;
export type ServiceOrdersPriorityEnum = typeof ServiceOrdersPriorityEnum[keyof typeof ServiceOrdersPriorityEnum];


/**
 * Check if a given object implements the ServiceOrders interface.
 */
export function instanceOfServiceOrders(value: object): value is ServiceOrders {
    return true;
}

export function ServiceOrdersFromJSON(json: any): ServiceOrders {
    return ServiceOrdersFromJSONTyped(json, false);
}

export function ServiceOrdersFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceOrders {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'vehicleId': json['vehicleId'] == null ? undefined : json['vehicleId'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'status': json['status'] == null ? undefined : json['status'],
        'type': json['type'] == null ? undefined : json['type'],
        'category': json['category'] == null ? undefined : json['category'],
        'maintenanceNature': json['maintenanceNature'] == null ? undefined : json['maintenanceNature'],
        'impact': json['impact'] == null ? undefined : json['impact'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'description': json['description'] == null ? undefined : json['description'],
        'serviceDate': json['serviceDate'] == null ? undefined : (new Date(json['serviceDate'])),
        'cost': json['cost'] == null ? undefined : json['cost'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function ServiceOrdersToJSON(json: any): ServiceOrders {
    return ServiceOrdersToJSONTyped(json, false);
}

export function ServiceOrdersToJSONTyped(value?: ServiceOrders | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'vehicleId': value['vehicleId'],
        'userId': value['userId'],
        'status': value['status'],
        'type': value['type'],
        'category': value['category'],
        'maintenanceNature': value['maintenanceNature'],
        'impact': value['impact'],
        'priority': value['priority'],
        'description': value['description'],
        'serviceDate': value['serviceDate'] == null ? value['serviceDate'] : value['serviceDate'].toISOString().substring(0,10),
        'cost': value['cost'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    };
}

