/* tslint:disable */
/* eslint-disable */
/**
 * Travel Manager - API de Gestão de recursos de transporte rodoviário
 * Especificação modular da API de back-end. Todos os schemas e paths estão em ficheiros separados (specs/). Use um agregador OpenAPI (como o ReDoc ou Swagger UI) para visualizar a documentação completa.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ferdxavier@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../../runtime';
/**
 * Representação completa de um motorista da empresa.
 * @export
 * @interface Driver
 */
export interface Driver {
    /**
     * ID único gerado pelo sistema.
     * @type {string}
     * @memberof Driver
     */
    id: string;
    /**
     * Nome do motorista.
     * @type {string}
     * @memberof Driver
     */
    name: string;
    /**
     * Número do CPF (apenas dígitos).
     * @type {string}
     * @memberof Driver
     */
    cpf?: string;
    /**
     * Número do RG (ex: MG 13.569.569).
     * @type {string}
     * @memberof Driver
     */
    rg?: string;
    /**
     * Data de Nascimento (formato YYYY-MM-DD).
     * @type {Date}
     * @memberof Driver
     */
    dateBirth: Date;
    /**
     * Número da Carteira Nacional de Habilitação (CNH).
     * @type {string}
     * @memberof Driver
     */
    cnhNumber: string;
    /**
     * Data de validade da CNH.
     * @type {Date}
     * @memberof Driver
     */
    validityCnh: Date;
    /**
     * Data de validade do exame toxicológico.
     * @type {Date}
     * @memberof Driver
     */
    validityToxicological: Date;
    /**
     * Timestamp de criação do registro.
     * @type {Date}
     * @memberof Driver
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the Driver interface.
 */
export function instanceOfDriver(value: object): value is Driver {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('dateBirth' in value) || value['dateBirth'] === undefined) return false;
    if (!('cnhNumber' in value) || value['cnhNumber'] === undefined) return false;
    if (!('validityCnh' in value) || value['validityCnh'] === undefined) return false;
    if (!('validityToxicological' in value) || value['validityToxicological'] === undefined) return false;
    return true;
}

export function DriverFromJSON(json: any): Driver {
    return DriverFromJSONTyped(json, false);
}

export function DriverFromJSONTyped(json: any, ignoreDiscriminator: boolean): Driver {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'cpf': json['cpf'] == null ? undefined : json['cpf'],
        'rg': json['rg'] == null ? undefined : json['rg'],
        'dateBirth': (new Date(json['dateBirth'])),
        'cnhNumber': json['cnhNumber'],
        'validityCnh': (new Date(json['validityCnh'])),
        'validityToxicological': (new Date(json['validityToxicological'])),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function DriverToJSON(json: any): Driver {
    return DriverToJSONTyped(json, false);
}

export function DriverToJSONTyped(value?: Driver | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'cpf': value['cpf'],
        'rg': value['rg'],
        'dateBirth': value['dateBirth'].toISOString().substring(0,10),
        'cnhNumber': value['cnhNumber'],
        'validityCnh': value['validityCnh'].toISOString().substring(0,10),
        'validityToxicological': value['validityToxicological'].toISOString().substring(0,10),
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    };
}

