/* tslint:disable */
/* eslint-disable */
/**
 * Travel Manager - API de Gestão de recursos de transporte rodoviário
 * Especificação modular da API de back-end. Todos os schemas e paths estão em ficheiros separados (specs/). Use um agregador OpenAPI (como o ReDoc ou Swagger UI) para visualizar a documentação completa.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ferdxavier@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../../runtime';
import type { PassengerReportReason } from './PassengerReportReason';
import {
    PassengerReportReasonFromJSON,
    PassengerReportReasonFromJSONTyped,
    PassengerReportReasonToJSON,
    PassengerReportReasonToJSONTyped,
} from './PassengerReportReason';

/**
 * Dados coletados de passageiros via link público/QR Code. Anónimo e leve.
 * @export
 * @interface CreatePassengerReportRequest
 */
export interface CreatePassengerReportRequest {
    /**
     * ID do veículo (obtido via QR Code).
     * @type {string}
     * @memberof CreatePassengerReportRequest
     */
    vehicleId: string;
    /**
     * Breve descrição do problema (máx. 250 caracteres).
     * @type {string}
     * @memberof CreatePassengerReportRequest
     */
    description: string;
    /**
     * 
     * @type {PassengerReportReason}
     * @memberof CreatePassengerReportRequest
     */
    reportReason: PassengerReportReason;
    /**
     * Imagem opcional do problema em Base64.
     * @type {string}
     * @memberof CreatePassengerReportRequest
     */
    imageBase64?: string | null;
    /**
     * Vídeo curto opcional do problema em Base64 (máx. 10MB).
     * @type {string}
     * @memberof CreatePassengerReportRequest
     */
    videoBase64?: string | null;
}



/**
 * Check if a given object implements the CreatePassengerReportRequest interface.
 */
export function instanceOfCreatePassengerReportRequest(value: object): value is CreatePassengerReportRequest {
    if (!('vehicleId' in value) || value['vehicleId'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('reportReason' in value) || value['reportReason'] === undefined) return false;
    return true;
}

export function CreatePassengerReportRequestFromJSON(json: any): CreatePassengerReportRequest {
    return CreatePassengerReportRequestFromJSONTyped(json, false);
}

export function CreatePassengerReportRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePassengerReportRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'vehicleId': json['vehicleId'],
        'description': json['description'],
        'reportReason': PassengerReportReasonFromJSON(json['reportReason']),
        'imageBase64': json['imageBase64'] == null ? undefined : json['imageBase64'],
        'videoBase64': json['videoBase64'] == null ? undefined : json['videoBase64'],
    };
}

export function CreatePassengerReportRequestToJSON(json: any): CreatePassengerReportRequest {
    return CreatePassengerReportRequestToJSONTyped(json, false);
}

export function CreatePassengerReportRequestToJSONTyped(value?: CreatePassengerReportRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'vehicleId': value['vehicleId'],
        'description': value['description'],
        'reportReason': PassengerReportReasonToJSON(value['reportReason']),
        'imageBase64': value['imageBase64'],
        'videoBase64': value['videoBase64'],
    };
}

