/**
 * Gerenciamento de Veículos API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Representação de um veículo cadastrado no sistema.
 */
export interface VehicleDto { 
    /**
     * ID único do veículo.
     */
    id: string;
    /**
     * Marca do veículo (ex: Toyota, Ford).
     */
    brand: string;
    /**
     * Modelo do veículo (ex: Corolla, F-150).
     */
    model: string;
    /**
     * Ano de fabricação do veículo.
     */
    year: number;
    /**
     * Cor do veículo.
     */
    color: string;
}

